### ISSUE TITLE
Conditional rendering with multiple portals

### ISSUE THREAD

**Issue by cretueusebiu** [LinusBorg/portal-vue#104]
When you have `<portal-target multiple>`  and try to render multiple portals with a `v-if`, it replaces all the content instead of just showing that one.

Example:
https://codepen.io/anon/pen/LQpgxd?editors=1010

It shows `modal1` and when you click on the toggle button it should show both, `modal` and `modal2`. 
But instead it will replace it. If you click a few more times it starts working.

This only happens when you use a custom component inside `<portal>`.

**Comment by LinusBorg** [comment]
Thanks for reporting this. Strange behaviour, will take some time to look into this probably, and I'm short on time right now. 

So please be patient, I won't be able to tackle this shortly.

**Comment by LinusBorg** [comment]
FYI, I won't find much time to work actively on this lib until mid-march, so thanks in advance for your patience.

**Comment by cretueusebiu** [comment]
I just used `v-show` instead. 

I tried to look for the problem myself, but it seems that in `portal-target.js` if you `console.log(this.children)` in the render function you'll always get the correct children that need to be rendered, however Vue doesn't seem to do that.

**Comment by LinusBorg** [comment]
Can'T reproduce with latest Vue version (2.5.16), but it should obviously work with 2.5.10 as well :/

**Comment by cretueusebiu** [comment]
Works as expected with Vue >= 2.5.14.
