### ISSUE TITLE
Will portal-vue work in this scenario?

### ISSUE THREAD

**Issue by lloydjatkinson** [LinusBorg/portal-vue#110]
I have a Vue component which wraps a third party map [library](https://github.com/yigityuce/Leaflet.Control.Custom) that controls it's own DOM. The Vue component mostly uses  watchers manually calling functions provided by the third party library when a data property is updated.

The library allows for custom controls to be added to it's DOM. However, this process involves manually writing inline HTML and then creating event callbacks. If I need to call methods on the Vue component I need to pass in the current instance. Furthermore, if I want to add basic interactivity to the new map controls, I currently have to use jQuery.

The following code is a simple example of this, and it can quickly become unwieldy amounts of jQuery and spaghetti code.

```
watchers: {
    someMapMarkers: function (state) {
        this.mapObject.updateMarkers(state);
    }
},
methods: {
    configureMapControls () {
        const vue = this;
        
        L.control.custom({
            position: 'topright',
            content:
                '<button type="button" class="toggle">'+
                  'Toggle some layer' +
                '</button>'
            events: {
                click: function(data) {
                    if (data.id === 'toggle') {
                        $('someSelector').hide();
                        vue.callSomeMethod();
                    } else if (vue.canShow) {
                        $('someSelector').show();
                    }
                    }
                },
                contextmenu: {
                    // Some other complex mess of jQuery selectors, all manual code, no Vue components.
                }
            }.addTo(this.mapObject);
        });
    }
},
// Need to use mounted() as the DOM will not be ready for the map.
mounted: {
    //setup map
    this.mapObject = ...;
    this.configureMapControls();
}
````

Ideally, I'd be able to pass in a Vue component to the map control, to replace the inline HTML, event handling, etc. Would portal-vue allow me to do this? The main problem I see is that the third party library is in control of it's DOM, and I don't know if either it or Vue will run first.

**Comment by LinusBorg** [comment]
I don't think portal-vue will be of mic help here. 

But is this a Leaflet map? There's vue wrappers for this lib...
