### ISSUE TITLE
Question: Is there a way to know if the portal is empty?

### ISSUE THREAD

**Issue by rijkvanzanten** [LinusBorg/portal-vue#111]
Hi! Thanks for creating this awesome plugin 😄

I was wondering if there is a way to check if `<portal-target>` has been passed content? In "regular" Vue, I would check if `this.$slots.default` has data.

I think I should be able to achieve a similar effect by adding a `ref` to the `portal-target` element and checking the refs `children`, but I'm very curious if there is a better way to do this 🙂

**Comment by LinusBorg** [comment]
It's in the documentation:

https://linusborg.github.io/portal-vue/#/docs/wormhole?id=hascontentfor

**Comment by thomasowow** [comment]
~~New documentation link: https://portal-vue.linusb.org/api/wormhole.html~~

V2 documentation link: https://v2.portal-vue.linusb.org/api/wormhole.html

**Comment by sidouglas** [comment]
and another updated link 🤣 ?

**Comment by thomasowow** [comment]
> and another updated link 🤣 ?

Updated the old link on https://github.com/LinusBorg/portal-vue/issues/111#issuecomment-602485086 to v2.

In the newer version it seems that their API has changed. I think you will need to utilize the [`change`](https://portal-vue.linusb.org/api/portal-target.html#change) event with its `hasContent` or `sources` properties on `portal-target`. 

I have not tested this.
