### ISSUE TITLE
Use case: Mapbox GL

### ISSUE THREAD

**Issue by davestewart** [LinusBorg/portal-vue#112]
We have a Mapbox GL component we want to move around the app, to save re-setting it up, and to save state, etc.

I've just tried doing something similar with the simple example and some HTML video (just to see what would happen) but no luck as the video starts from the beginning again:

- https://codepen.io/davestewart/pen/LQBVMq

Is this the case for complex components?

**Comment by LinusBorg** [comment]
portal-vue moves the virtual dom nodes, not the DOM elements.

So when switching a portal from disabled to enabled and sending some local slot content to a portal-target, the portal-target will create fresh DOM elements.

So yeah, that behaviour is expected due to how the portal works.

**Comment by davestewart** [comment]
Can we move it around using `$mount`?

I know there is [this thread](https://forum.vuejs.org/t/add-component-to-dom-programatically/7308/13) with quite a lot of info in.

**Comment by LinusBorg** [comment]
Well, that's something we should discuss on the forum, as it's not related to portal-vur anymore. 

Can I close this?

**Comment by davestewart** [comment]
Sure thing :)
