### ISSUE TITLE
Component's local state is reset when toggling disable / switching targets

### ISSUE THREAD

**Issue by erezsh** [LinusBorg/portal-vue#113]
For example, say I have

    <portal to="dest" :disabled="disabled")
      <stateful-component/>
    </portal>
    <portal-target name="dest"/>

    <button @click="enable_portal">Enable</button>

Clicking the button will activate the portal, but everything inside the components' data will be reset (for example, input boxes reset their value too). I assume because it's deleted and then recreated. Am I doing something wrong?

**Comment by LinusBorg** [comment]
A concrete example on jsfiddle would be helpful, but while I cant check right now, this might be an unavoidable side effect.

**Comment by erezsh** [comment]
As requested, a jsfiddle demonstration: https://jsfiddle.net/erezshin/oLwuthsf/

I can think of two possible solutions:

1) Find a way to *move* an element in DOM without removing and inserting it again

2) If 1 is impossible, save the components' data (state can be mapped via :model etc.) and set it again after it's recreated in the new location.

**Comment by erezsh** [comment]
I should also note that it seems possible. The following code:

    cb = $('input')
    cb.parentNode.appendChild(cb.cloneNode())

Copies the checkbox while maintaining the state.

**Comment by LinusBorg** [comment]
Uhm, I just took a look at your demo, and it doesn't really demonstrate what you are claiming:

For starters, there's not child component, so there's no child component state to be lost.

**Comment by LinusBorg** [comment]
But ok, so I've been able to simulate what you initially claimed in the OP:

https://jsfiddle.net/qt0838zs/

I think this may be unavoidable when using `disable`, unfortunately.

I will document this appropriately, and we will look into how to work around that if possible. But it's simply a result of portal-vue moving virtualDOM instead of real DOM (which was a design decision to be able to use other goodies like scoped slots and transitions.

**Comment by erezsh** [comment]
> I think this may be unavoidable when using disable, unfortunately.

I tried playing around with the `to` attribute as well, with the same effect. Is there another way to make a node go through a portal and back without resetting?

Btw, `cloneNode()` seems to work on vue components as well. I understand this may prevent other desirable features, but perhaps the scope of change is limited enough to add it as an option.

Anyway, maintaining state seems like an important feature to me. What you describe as the "Vue way", which is saving the entire state in the main app, seems wrong to me. It violates the concept of separation of concerns, and makes modularity more difficult, IMHO.

**Comment by LinusBorg** [comment]
>  Is there another way to make a node go through a portal and back without resetting?

I would have told you if there were, wouldn't you think?

> but perhaps the scope of change is limited enough to add it as an option.

No, that behaviour is so fundamentally different that I would not want to mix them in this library. 

> Anyway, maintaining state seems like an important feature to me. What you describe as the "Vue way", which is saving the entire state in the main app, seems wrong to me. It violates the concept of separation of concerns, and makes modularity more difficult, IMHO.

You are mixing two things here.

First, I never argued to keep "the entire state in the main app", I simply said that when dealing with e.g. an input element's state (as you did in *your* fiddle), you should not mess with it directly but use Vue's data binding for that.

If you don't want to do that and instead manipulate the DOM directly, then Vue might not be the library you want.

Second, when we talk about components( not DOM elements), as I showed in *my* fiddle, I agree that it's unfortunate that at right now, local state will be reset when e.g. toggling `disable`, but I can't provide an immediate solution. I already said I will look into it, so please be patient or dig into the source and help me fix it. :)
