### ISSUE TITLE
Dynamically created targets

### ISSUE THREAD

**Issue by ronnieoverby** [LinusBorg/portal-vue#114]
Is it possible to dynamically create portal targets in response to UI interactions?

My use case is that I want to render a vue template inside part of the DOM managed by a jQuery plugin. I want the jQuery plugin to create a `portal-target` and then I want to wire it up to a pre-existing `portal`.

I've tried using the Wormhole object, but I'm not getting anything to work.

Thanks!

**Comment by ronnieoverby** [comment]
A little more context about my use-case: I am placing my jQuery plugin (datatables) within a `v-pre` element.

I'd like for the plugin to create a `portal-target` and voila, you see the content from the portal.

Thanks, again.

**Comment by LinusBorg** [comment]
PortalTarget is just a component, and components are just Vue instances, so you can generally mount a component manually so some place:
```javascript
import { PortalTarget } from 'portal-vue'

const Constr = Vue.extend(PortalTarget)
const target = new Constr().$mout(document.getElementById('idOfElement'))
```

How to do that in the context of datatables I have no idea, since I don't use that plugin.

**Comment by ronnieoverby** [comment]
Why did you first extend `PortalTarget`?

**Comment by LinusBorg** [comment]
Probably out of habbit to have a reusable constructor.

**Comment by LinusBorg** [comment]
Closing since I think the question is answered
