### ISSUE TITLE
Use Case: Keep content rendered/cached once

### ISSUE THREAD

**Issue by isometriq** [LinusBorg/portal-vue#115]
Responded here with a suggestion of portal-vue here
https://stackoverflow.com/questions/47560502/vue-router-use-keep-alive-to-cache-certain-components/49080081#49080081

Essentially, the use case is loading rich or heavy content on a page (like a video, a threejs model, etc) on a page and keep it accessible for use somewhere else or just later on the same page (while using the same instance or that content). The idea here is to have the content in a "portal" outside the components (at the root) and use the "portal targets" to place the content inside any component.

Although I'm not sure if that would work, it could be a good idea to test.

Note that `<keep-alive>` may be well enough, so this is more for complex navigation cases.

**Comment by isometriq** [comment]
This pattern could looks like stores for state, except it would be for rendered components/content

**Comment by LinusBorg** [comment]
I just had a similar question recently in #112.

The short answer is: No, Portal-Vue can't do that right now. It caches virutaldom nodes, and when switching targets or enabling/disabling a portal, Vue will generate new elements for this virutal DOM, so it can't be used to cache heavy elements in the way you imagine.

**Comment by LinusBorg** [comment]
I will close this since I think the Question is resolve and OP didn't reply to the contrary,
