### ISSUE TITLE
this.$el is an empty div?

### ISSUE THREAD

**Issue by nickforddesign** [LinusBorg/portal-vue#117]
I noticed that after wrapping some of my components in portal components, my `this.$el.querySelector` calls were returning null. 

I put together this demo to make sure that it wasn't some other issue, and sure enough, inside <portal> components, `this.$el` is the empty target div. I can work around this by using `document.querySelector`, but I found this behavior a bit puzzling.

https://codesandbox.io/s/6xmzmrm50r

Maybe it's not a big deal, but it definitely seems less than ideal, because I don't this `this.$el` is usable if it's not representative of the actual component. 

If there is any concern that we shouldn't be relying on `this.$el` anyway, I'm using it to focus a button on a child component. I'm open to other suggestions if that isn't recommended.

**Comment by LinusBorg** [comment]
You defined the `Portal` component as the root element of your component, so `this.$el` points to the root element rendered by the portal. That element is an empty div. Why?

Well, the slot content that you passed to the `<portal>` component is rendered somewhere else in the DOM, so those elements are not children of the `this.$el` element - they are somewhere else in the DOM, as you wanted them to be ;)

So assuming that you really want to get access to the `<div class="test">` element, simply use a `ref`

https://codesandbox.io/s/843n23j3ol

**Comment by nickforddesign** [comment]
Okay got it, thank you very much for the clarification!
