### ISSUE TITLE
Documentation site seems to be down

### ISSUE THREAD

**Issue by phegman** [LinusBorg/portal-vue#119]
Heads up... https://linusborg.github.io/portal-vue/ appears to be down for me.

Thanks for this great component!

**Comment by LinusBorg** [comment]
thanks for the info.

But it's up for me right now, can you check again @phegman ? Maybe it was a short outage with githu pages?

**Comment by phegman** [comment]
Yep back up, thanks! Not sure, could have been an issue with Github pages
