### ISSUE TITLE
detect duplicate targets

### ISSUE THREAD

**Issue by uptownhr** [LinusBorg/portal-vue#122]
don't know if there are any technical challenges here but it would be great if duplicate target declarations can be detected with warnings throwns. I know the teams using the component can have  better coding standards to account for this but as teams get larger, it can cause unnecessary debugging times. A wish :)

**Comment by LinusBorg** [comment]
I have indeed thought wether it would make sense that portal-target components register themselves globally, that would probably be able to solve this. I won't be a priority issue though, I have quite some cleaning up to do before that, and hardly find time for that.

**Comment by uptownhr** [comment]
:) gotcha.
