### ISSUE TITLE
Breaks provide/inject

### ISSUE THREAD

**Issue by theoephraim** [LinusBorg/portal-vue#126]
I am trying to use portal-vue some popups but it breaks the provide/inject functionality of vue.

It makes sense with how provide/inject works but I was wondering if you had thought about this?

http://jsfiddle.net/crv15stx/1/

**Comment by LinusBorg** [comment]
You're right, the basic mechanism of the portal makes it complicated to keep some of the "parent<-> child" related features working. So far I foud partial solutions, but haven't found a way to keep them all working at the same time (but I'm not done yet).
