### ISSUE TITLE
Update build to avoid automagically installing on window.Vue

### ISSUE THREAD

**Issue by Alfredo-Delgado** [LinusBorg/portal-vue#127]
Portal-Vue is an excellent tool for methodically building up an application component tree on legacy web pages that may be suffering from JS spaghetti and/or state in DOM hell.

There are scenarios where a Vue instance in proper new code that's built and bundled has to co-exist with a global Vue instance loaded via a script tag.

However, portal-vue currently has code that automagically installs itself in window.Vue if window.Vue is found:
https://github.com/LinusBorg/portal-vue/blob/cf07699611ac82f8ec1dc8debbfd6bb1f8fed733/src/index.js#L9-L11

There should be a build available that does not include this unwanted behavior.

**Comment by emileber** [comment]
I did exactly that on vue-i18n: https://github.com/kazupon/vue-i18n/pull/291

**Comment by LinusBorg** [comment]
Thanks  @emileber - Unfortunately the stucture of this lib doesn't allow to move the install hook into some constructor.

I may have to consider separate builds.

**Comment by LinusBorg** [comment]
Will be solved in 2.0

https://github.com/LinusBorg/portal-vue/blob/c360beac6af6475b610950a2da000ab1a0c983c2/src/index.ts#L25-L33
