### ISSUE TITLE
Default Slot Content for Portal-Target Not re-rendering on updates

### ISSUE THREAD

**Issue by dts** [LinusBorg/portal-vue#131]
I'm couldn't find anything related to this (i.e. known issue, intended behavior, etc), but there appear to be some issues with reactivity in the "default slot".  I have an example pen here:

https://codepen.io/anon/pen/dKpRoe

I'd expect the default content to be reactive (i.e. have incrementing numbers).

This used to work, but after some Vue updates it stopped working.  Not sure what's up.  I've worked around it (now that I've actually pinned down the issue), but it'd be good to add a note in the "default slot" section of the docs noting this issue.

**Comment by LinusBorg** [comment]
Thank's I'll look into it.

**Comment by LinusBorg** [comment]
Note to self: compued property `children` in Target won't update when the default slot content changes as the `$slots` object it's reactive. 

#### Solution

Turn `children` into a method.
