### ISSUE TITLE
How to use portal to clone content?

### ISSUE THREAD

**Issue by paulgeisler** [LinusBorg/portal-vue#134]
I simple cannot achieve **cloning**. I need a button from header to be cloned into the hero section. The examples for this purpose are rare and i tried everything i could find. What's wrong with my code?

```
// header.vue (pug syntax)
portal(to="contact-button-container")
    my-link(slot-scope="_", :href='buttonTarget')
```

```
// hero.vue (pug syntax)
portal-target(name='contact-button-container' slim)
```

The button appears only in one place. By trying around with `:disabled="transferContactBtn"` it's either header or hero but never both.

**Comment by LinusBorg** [comment]
Cloning hasn't been a real feature so far - maybe it should be.

Until then, you will have to use a little woraround with a functional component wrapping the portal:

```javascript
export default {
  name: 'cloning-portal'
  functional: true,
  render(h, { data, scopedSlots }) {
    return [
      scopedSlots.default(),
      h('portal-vue', data, scopedSlots.default())
    ]
  }
}
```

Usage would be: 

```html
<cloning-portal to="contact-button-container">
  <my-link slot-scope="_" :class="{'hide' : subpageLayout}", :destination='buttonTarget' />
</cloning-portal>
```

**Comment by paulgeisler** [comment]
Thank you for quick reply!

I can't make it work and don't know why...

https://codesandbox.io/s/5mjo9r63k
