### ISSUE TITLE
Slot props are not reactive

### ISSUE THREAD

**Issue by altinselimi** [LinusBorg/portal-vue#137]
Would it be possible to have passed slot props reactive, like data objects are by default. I'm finding it impossible to achieve that. You can check the example here in this [codepen](https://codepen.io/altinselimi/pen/yqbjpv).

**Comment by LinusBorg** [comment]
Hm, seems to be a bug, should work imho.

**Comment by LinusBorg** [comment]
I updated the vue version of the codepen ( was 2.2.something) to the latest, and changed the slot-scope to 
```
slot-scope="{message}"
```
and it works: https://codepen.io/LinusBorg/pen/gjWKPR
