### ISSUE TITLE
Unable to select elements in PortalTarget with Testcafe

### ISSUE THREAD

**Issue by curtisblackwell** [LinusBorg/portal-vue#138]
Have you played around with portals in Testcafe? (#2 and #43 came up in search results.) I'm having difficulty selecting elements in portals to interact with.

I already use [testcafe-vue-selectors](https://github.com/DevExpress/testcafe-vue-selectors) with other components successfully. I tried using
- `VueSelector('PortalTarget')`,
- `VueSelector('Portal')`, 
- `VueSelector('portalTarget')`, and
- `VueSelector('portal')`.

On each of those, I tried using `.find('.qa-close-modal-button')`, but it doesn't work. I can confirm it worked before switching to portal-vue.

I also tried nesting them in separate components and selecting the elements directly with `Selector()`.

**Comment by LinusBorg** [comment]
I thought about using test café for a while but never came around to actually doing so. 

So no, I have no experience with test café and can't really share any tips or general pointers.

**Comment by curtisblackwell** [comment]
Okay, thanks. I'll come back and leave a comment if I end up figuring it out. For now, we're skipping over it since this specific test is somewhat low value.

**Comment by curtisblackwell** [comment]
For anyone who runs into this, I ended up being able to use TestCafe's built-in `Selector()` instead of the `VueSelector()` to target the element in this test.

Still not sure why sometimes one or the other is needed, but that's a TestCafe issue, not a portal-vue one.
