### ISSUE TITLE
Bundle imports Vue while using window.Vue

### ISSUE THREAD

**Issue by remarks** [LinusBorg/portal-vue#140]
While using window.Vue and a Webpack build on top of it, [PortalVue still imports the whole distribution of Vue into the build](https://github.com/LinusBorg/portal-vue/blob/develop/dist/portal-vue.js#L9). I'm guessing [the import in this file](https://github.com/LinusBorg/portal-vue/blob/develop/src/components/portal.js#L1) is due to when [the package was using .vue files initially](https://github.com/LinusBorg/portal-vue/commit/e4ec5bcfc62e2e12cff85676fd53326eee208c24).

I've [forked the build here](https://github.com/remarks/portal-vue/commit/833e8502a74b8eb5fc875581ca11d3055ece6909) and it's running as expected I think.

**Comment by LinusBorg** [comment]
I'm not sure I understand what you describe. 

The import statements in the component would receive whatever your app's webpack build gives it  hen it asks for 'vue'. 

You say you are using window.Vue and webpack - have you purposely externalized Vue?

**Comment by remarks** [comment]
Sorry, `externals` fixed it. Thanks!
