### ISSUE TITLE
Suggestion: use PascalCase default component names instead of camelCase

### ISSUE THREAD

**Issue by tinymachine** [LinusBorg/portal-vue#146]
Currently `portal-vue` defaults to camelCase component names (`'portal'` and `'portalTarget'`):

https://github.com/LinusBorg/portal-vue/blob/b67fd3bdbea67afdf130305a85a7fae2d24aa149/src/index.js#L5-L8

I think if these were changed to PascalCase (`'Portal'` and `'PortalTarget'`), that would allow either kebab-case (`<portal></portal>`) or PascalCase (`<Portal></Portal>`) component names to be used in templates, unlike the camelCase versions, which appear to require you to manually set the `portalName` and `portalTargetName` options on installation if you want to use PascalCase component names:

```js
Vue.use(PortalVue, { portalName: 'Portal', portalTargetName: 'PortalTarget' })
```

Since PascalCase component names seem to be [encouraged in the Vue Style Guide][1] for single-file components, supporting them by default would be great!

Also, just curious: per the Vue Style Guide, it seems like the `portal` component should have [multi-word name][2], no? Maybe I'm misunderstanding.

Thanks for contributing this plugin to the Vue community, and for your tireless work on the Vue forum and elsewhere -- I've learned a lot from your responses (and am amazed and humbled that you're not a professional developer!). Cheers.

[1]: https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended
[2]: https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

**Comment by LinusBorg** [comment]
Good suggestions, shjould be easy enough to do.

> Also, just curious: per the Vue Style Guide, it seems like the portal component should have multi-word name, no? Maybe I'm misunderstanding.

Indeed, but this lib was created before the style guide existed, and renaming component default names now would be a breaking change, so I might consider it before the next major.

**Comment by tmorehouse** [comment]
@LinusBorg re portal component tag, maybe it would be possible to export the original name plus a new name in the plugin version?

`portal/Portal` and perhaps `portal-source/PortalSource`?

**Comment by LinusBorg** [comment]
That might be a good idea, thanks
