### ISSUE TITLE
Doc site broken

### ISSUE THREAD

**Issue by shawn-sandy** [LinusBorg/portal-vue#150]
Not sure if Im the only one having this problem but the Doc site is broken both Chrome / IE works in FireFox, Mac/Pc. https://linusborg.github.io/portal-vue/#/

![image](https://user-images.githubusercontent.com/38263979/46390455-ecd3b100-c6a5-11e8-83a3-dfce94309315.png)

Thanks 
- Shawn

**Comment by LinusBorg** [comment]
Hey @shawn-sandy is that still happening for you? I can't reproduce it in Chrome, FF or Safari on Mac

**Comment by shawnsandy** [comment]
Same issue - still only works in FF

**Comment by LinusBorg** [comment]
Weird.

Works for me on FF, Chrome, (Win&Mac) Safari (Mac). 

It doesn't work in IE in my office, but that is indeed possible as I didn't give a damn about IE for the docs page ^^

**Comment by ellefsen** [comment]
Doesn't work here either.
Chrome Version 69.0.3497.100
macOS High Sierra 10.13.6 (17G65)

**Comment by LinusBorg** [comment]
Weird. Can't reproduce it for the live of me, on Win or Mac

**Comment by LinusBorg** [comment]
I'll move the docs to vuepress

**Comment by belvederef** [comment]
This happens to me as well. Using Chromium 70.0.3538.77 on Arch Linux

**Comment by idlinnes** [comment]
same. Chrome 70.0.3538.102 (Official Build) (64-bit) Win10

**Comment by mandaputtra** [comment]
```
ReferenceError: docuteIframe is not defined[Learn More] config.js:28:13
    <anonymous> https://linusborg.github.io/portal-vue/config.js:28
```

Only got this. from Firefox Nightly 66.

**Comment by LinusBorg** [comment]
So I'm working on a small PR to move this to docute4 in hopes of making it work again with minimal effort.

**Comment by LinusBorg** [comment]
I upgraded the docute dependency of the v1 docs and re-redeployed them here:

https://v1.portal-vue.linusb.org

New 2.0 Docs are here: https://portal-vue.linusb.org
