### ISSUE TITLE
portal-vue with vue-router and <KeepAlive/>

### ISSUE THREAD

**Issue by AfikDeri** [LinusBorg/portal-vue#155]
Hi all,

I have a VueJS SPA, I manage my state with Vuex and handle routing with VueRouter.

My use case is this:
I have a steps form, each step has it's own content. at the bottom of the form I have the basic "Next" and "Back" buttons to navigate between the form steps and using VueRouter I'm switching routes based on the current step. I have a portal-target near the "Next" button that in a specific step will add an extra button called "Add Items".

#### Regular Step:
![image](https://user-images.githubusercontent.com/17595033/47971788-6d1e7500-e09d-11e8-85d3-f0813a830758.png)

#### Step with extra button:
![image](https://user-images.githubusercontent.com/17595033/47971793-7d365480-e09d-11e8-8031-d80bf54f267a.png)

The problem is that when the user is navigating to the next or previous steps this button is still showing, I'm guessing it happens because I have a `<keep-alive>` component wrapping my `<router-view>` and this is causing the previous step (that has that button) to still exist in the background.
I see the button inside the target even though I shouldn't.

Is there a workaround you have in mind?

**Comment by LinusBorg** [comment]
I would have to see a reproduction of the actual issue to understand what's going on.

**Comment by LinusBorg** [comment]
Ok so I tried to understand what'S going on from the description alone, and I think it's possible to make this work quite easily.

When a kept-alive component is activated and deactivated, lifecycle hooks by those respective names are fired. You can use those hooks to show/remove the portal and consequently, the button i the portal-target:
```html
<portal v-if="showAddButton" to="someName">
  <button>Add Item</button>
</portal>
```
```javascript
export default {
  data() {
    return {
      showAddButton: true,
    }
  },
  activated() {
    this.showAddButton = true,
  },
  deactivated() {
    this.showAddButton = false,
  }
}
```

**Comment by AfikDeri** [comment]
@LinusBorg  Ohh, that's a great solution, I'll try it out.
BTW, I didn't notice you already posted an answer here so I've created an example project to illustrate the issue better incase anyone else is interested.

Here it is:
https://bitbucket.org/DeriAfik/portal-vue-steps-example

I'll try your solution right away, sounds like it's gonna work.

**Comment by Samuel87** [comment]
If anyone else stumbles on this like me, I elegantly solved it with a wrapper component. I had the PortalTarget as slot content to a toolbar above the second RouterView (which was wrapped with KeepAlive) to add dynamic content based on the page. My issue was that the PortalTarget kept old content when a new page didn't add anything to it.

```html
// PortalRenderer.vue

<template>
  <portal v-if="activated" :to="to">
    <slot />
  </portal>
</template>
```

```js
export default {
  props: {
    to: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      activated: true,
    }
  },
  activated() {
    this.activated = true
  },
  deactivated() {
    this.activated = false
  },
}

```

**Comment by LefterisMavrakis** [comment]
Hello guys. I had the same problem with <keep-alive> on <vue-router> and ive tried so many things to make portals properly work. LinusBorg solution with activated and deactivated hook was the perfect and simplest. Thanks for that and for your participation in Vue.js. Keep up with the good work!!
