### ISSUE TITLE
Weird bug causing portal component losing all states & refs

### ISSUE THREAD

**Issue by nodegin** [LinusBorg/portal-vue#159]
[See the bug in action](https://codesandbox.io/s/34y29l5j8p)

This seems is a portal-vue internal bug, currently I am using the `display` hack as workaround.

In case codesandbox link dead:
[vue-portal-slots.zip](https://github.com/LinusBorg/portal-vue/files/2609247/vue-portal-slots.zip)

**Comment by nodegin** [comment]
Another interesting behavior: if you edit Vuex store state `smallScreen` to true

The bug will be deferred for 1 tick

[demo](https://codesandbox.io/s/6w419rkp83)

**Comment by LinusBorg** [comment]
Hey @nodegin I just published 1.5.1-beta.0, you can install it with the `next` tag:
```bash
npm i portal-vue@next
```

Please test this version and report back if your issue is fixed - it should be.

**Comment by LinusBorg** [comment]
Nevermind, this path release won't fix it either. In fact, after taking a second look I think there's not much we could do.

In the part of your example that is the "bug", you are, by using `v-if`, destroying the portal and all of its children - which included the stateful component.

And in the other target that you are switching to, the component has to be re-created.

There isn't really anything we can do about this, I think. Sorry.
