### ISSUE TITLE
feat(portal): consider rendering placeholder comment when slim=true and only one child

### ISSUE THREAD

**Issue by tmorehouse** [LinusBorg/portal-vue#161]
In the `portal` component, currently the prop `slim` only applies when the portal is disabled.

The portal component always renders a placeholder tag, (when content is sent to the `portal-target`) which can disrupt some layout depending on where it is placed (and type of tag) in the users markup.

I suggest allowing "slim" to apply to the placeholder element as well.  Vue will render a comment placeholder when you pass `false` to createElement (`h(false)`).  I suggest adding in a check in the render function to see if `children.length <=1` and if `this.slim` is `true`, to render the placeholder comment element when not `disabled`.

```js
  render(h) {
    const children = this.$slots.default || this.$scopedSlots.default || []
    const Tag = this.tag
    if (children.length && this.disabled) {
      // hack to make child components skip the portal when defining their $parent
      this.$options.abstract = true
      return children.length <= 1 && this.slim ? (
        children[0]
      ) : (
        <Tag>{this.normalizeChildren(children)}</Tag>
      )
    } else {
      if (this.slim && children.length <= 1) {
        return h(false) // renders `<!---->`
      } else {
        return (
          <Tag
            class={'v-portal'}
            style={'display: none'}
            key={'v-portal-placeholder'}
          />
        )
      }
      // h(this.tag, { class: { 'v-portal': true }, style: { display: 'none' }, key: 'v-portal-placeholder' })
    }
  }
```

**Comment by LinusBorg** [comment]
Yeah, that makes sense. 

Technically it's a breaking change, so I will include it in 2.0 (which will be the next release)

**Comment by tmorehouse** [comment]
`h(false)` is a nifty trick to use, and is real handy with render functions.  Its basically like `v-if`, but Vue doesn't know that it is a `v-if`... meaning that a `ref` to the component is still available even though "nothing" is rendered.  Slots are still accessible to the hidden component as well.  When using a standard SFC html template, one can't do this trick.

**Comment by tmorehouse** [comment]
Another option would be to allow the prop `tag` to be a boolean `false`, (or, alternatively, an empty string) and if it is `false` render the placeholder tag if the content is "slim", which would be more backwards compatible

**Comment by LinusBorg** [comment]
Will be part of [2.0.0](https://github.com/LinusBorg/portal-vue/tree/next)
