### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by karlos1337** [LinusBorg/portal-vue#166]
At this moment the library don't have any types so to be able to use it in my TS projects I need to do kind of ugly patching,  typescript support its on the roadmap?

**Comment by karlos1337** [comment]
Great! I'll be able to check and test it, looking forward to it :)

**Comment by LinusBorg** [comment]
@karlos1337 i pushed the new version in the `next` branch but still want to do some testing before publishing a beta or something.

You can take a look whenever you want though, of course.

**Comment by karlos1337** [comment]
I've testing it installing the branch as a npm package, the plugin can be "Vue.used" and the install function types seems correctly inferred but can't import wormhole, please, don't understand this as a formal incidence, I'll only tell you in case it can help. Did you think about adding wormhole as a global instance object? (https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins).

**Comment by LinusBorg** [comment]
> but can't import wormhole

Does that mean you can't import the wormhole? What happens? 

I think i he structure of exports yesterday to make names imports for wormhole and the other components work correctly, but forgot to build again before pushing the branch. That might be the cause. 

Thanks for trying it!

**Comment by superlucky84** [comment]
A type script version is required. When is 2.0.0 released?

**Comment by LinusBorg** [comment]
Sometime this month, hopefully.

**Comment by LinusBorg** [comment]
I just released the beta: https://portal-vue-next-preview.netlify.com/

Would be cool if you could check it out and see if the types all work as expected.

**Comment by LinusBorg** [comment]
this is now available in 2.0.0-beta
