### ISSUE TITLE
Docs example not working?

### ISSUE THREAD

**Issue by dgleba** [LinusBorg/portal-vue#167]
The example at https://linusborg.github.io/portal-vue/#/guide is not working.

In console..
  `unpkg.com/portal-vue@1.5.0/index.js:1 Failed to load resource: the server responded with a status of 404 ()`

The red text be in the right side.

![image](https://user-images.githubusercontent.com/4622715/50283416-d545d200-0423-11e9-9e14-e4516e30f1ec.png)

Using **https://cdn.jsdelivr.net/npm/portal-vue@1.5.0/dist/portal-vue.min.js** fixes it.

**Comment by LinusBorg** [comment]
Just opened the codepen, it works fine for me...

**Comment by LinusBorg** [comment]
Unpkg had some issues, not a problem with the example
