### ISSUE TITLE
Adding components to the same portal target makes them recreated

### ISSUE THREAD

**Issue by xgrn** [LinusBorg/portal-vue#169]
Hello.

I've got a strange behavior with multiple modal components in the same target. See the fiddle: https://jsfiddle.net/z64b3fu2/

It has a modal pop-up form and a global loading spinner both rendered in the modal portal target. Once you submit the form the spinner is added to the target. It works nice but the pop-up form component is destroyed as soon as the modal spinner appears.

To check this out click 'Show dialog', type anything to the form then click 'Start async action'. The form is cleaned up at this moment. Maybe I do anything wrong but I tried using keys and different order. It's still the same.

Thanks!

**Comment by LinusBorg** [comment]
Hm, thanks. Will have a look

**Comment by xgrn** [comment]
Thanks! This may be related to #159 and / or #141

**Comment by LinusBorg** [comment]
I'm a little stumped, to be honest. No idea where this is coming from.

**Comment by LinusBorg** [comment]
Got it! 🎯

Will release a bugfix release soon

**Comment by LinusBorg** [comment]
Hey @xgrn I just published 1.5.1-beta.0, you can install it with the `next` tag:
```bash
npm i portal-vue@next
```

Please test this version and report back if your issue is fixed - it should be.

**Comment by hivokas** [comment]
I've also faced this problem.
I will test version mentioned above as soon as possible.

**Comment by xgrn** [comment]
@LinusBorg That's great! Works like a charm. Thank you!

**Comment by hivokas** [comment]
@LinusBorg I've tested version with `next` tag and looks like all works like a charm! Thanks for quick feedback and fixing!

**Comment by slavarazum** [comment]
Good job, thanks for quick help!

**Comment by LinusBorg** [comment]
Awesome. Ill give it 24 hours or so to see if anything gets reported, then I'll make a proper release on master.

**Comment by LinusBorg** [comment]
@xgrn  @slavarazum @hivokas I just published 1.5.1, please upgrade.

**Comment by xgrn** [comment]
@LinusBorg Upgrading. Thank you again!
