### ISSUE TITLE
2.0 beta: Write Changelog / Migration guide

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#177]

**Comment by smithb1994** [comment]
Is there an ETA on the 2.0 release? I'm waiting on a 2.0 release.
Will it be Days? Weeks? Months?
Thanks

**Comment by LinusBorg** [comment]
A few weeks max. 

Beta is already out, see the `next` branch.

**Comment by smithb1994** [comment]
I noticed reactivity is still not available inside the portal, when I was testing next.
When I update data in the parent, it's not rendering in the portal.
Is this feature not going to be available in 2.0?

Thanks

**Comment by LinusBorg** [comment]
I haven't come accross any such bug, ole s open an issue with a reproduction. 

There was a big that sounds a bit like this, but it's solved in 1.5.1 and `next`

**Comment by smithb1994** [comment]
Here's a codepen example of what I'm talking about:
https://codepen.io/anon/pen/jdzaZr?editors=1010#0  

Model changes outside the portal are not picked up, but they are picked up when modified within the portal.

**Comment by LinusBorg** [comment]
A, I see. that seems to be an issue with Vue <2.3 - wans't able to pin down the exact version range affected, but it works when you just update the Vue version in your codepen.

**Comment by smithb1994** [comment]
HA! great find. Didn't even consider that. Might want to update the docs' codepen to reflect the new version of vue, to avoid that confusion. Works great now, thanks!

**Comment by LinusBorg** [comment]
Well the docs will be completely re-done for 2.0 anyways (https://portal-vue-next-preview.netlify.com/)
