### ISSUE TITLE
npm package contains jsx

### ISSUE THREAD

**Issue by korsarNek** [LinusBorg/portal-vue#179]
The package that gets installed via `npm install portal-vue` is not compiled down to plain js but contains jsx.
So the installation guide doesn't suffice and it's a bit annoying to have to transpile the dependencies. It would be great if that step would not be necessary.
I'm using portal-vue 1.5.1 and babel 7.

**Comment by LinusBorg** [comment]
Hm, if that's really the case that would be a publish error or something. 

You can check the content of /dist on master, it doesn't contain any jsx. 

How exactly are you including portal-vue?

Can you share an actual reproduction repository?

**Comment by korsarNek** [comment]
hmm, you are right, there's no jsx in dist. I'll try to recreate it in a fresh repo.

**Comment by korsarNek** [comment]
Ok, false alarm. I've found out what my mistake was. I was using PHPStorm and it decided to import PortalVue from the src directory when I started writing it in the template. Tried to reproduce it in vscode and everything worked fine.

**Comment by fatlinesofcode** [comment]
i get this behaviour too. Its really annoying. I think it could be avoid by removing the src folder from the npm package. I never have it occur on other packages.
