### ISSUE TITLE
Portal target content stays visible after route change

### ISSUE THREAD

**Issue by Eggwise** [LinusBorg/portal-vue#180]
First: Awesome project, good job Linus!

I think something is not working right ..

I have this code in my component

   ```
 <portal to="modal" :order="1" v-if="modal_visible">
      <div class="red-box">
        <h1>Modal visible ? {{modal_visible}}</h1>
      </div>
    </portal>
```

I have this portal target at the bottom of my body.

`<portal-target name="modal" multiple></portal-target>`

This works fine.
When i route to another page though, the content inside the portal target stays visible.
But the component in which i defined the content for the portal target has been destroyed.
Thus, i expect the content in the target to be gone aswell, but thats not the case.

Also i cannot interact with the rendered component after routing, it just stays there.

Any idea why this is happening?
Help is much appreciated!

Cheers

**Comment by LinusBorg** [comment]
Hm, not really. I'm routinely testing it with a router so it should work.

Can you reproduce the problem on jsfiddle / codesandbox.io?

**Comment by Eggwise** [comment]
Hi Linus,

Some more info:

It only happens when i route to a page with <keep-alive>
Some of my routes are kept alive for performance reasons.
But when i navigate to the "kept alive route" the portal content stays.

This is my route code

```
<div class="full-height full-width" style="">
    <keep-alive>
      <router-view v-if="$route.meta && $route.meta.keep_alive"></router-view>
    </keep-alive>

    <router-view v-if="!$route.meta || !$route.meta.keep_alive"></router-view>
  </div>
```

**Comment by Eggwise** [comment]
Created a codestandbox
https://codesandbox.io/s/jlo14mw6y5
Cannot reproduce it.


**but i discoverd**
In my app it only happens when i put the portal inside 
a slot within a slot

so i am going to test that in codebox


```
<some_component>
  
  <another_compent>
    <portal to="test" :order="1" >

      Content still visible on keep alive routes.
      ALso when this portal gets renderd it stacks, so the rendered content is visible 2 times on the keep alive rout

    </portal>
  </another_compent>
  
</some_component>
  
```

**Comment by Eggwise** [comment]
![image](https://user-images.githubusercontent.com/20506046/52473615-83553900-2b96-11e9-991c-4c48bf1e5ca7.png)

Modal keeps visible. 
Looks like the content is not destroyed properly

What does that $vm01 mean ?

**Comment by tmorehouse** [comment]
You may need to detect when the keep-alive is activated/deactivated (using livefycke hooks), and v-if your content out (i,e. modal component).

Since it is in a keepalive, the rendered content of Portal is still "alive" and does not get destroyed.  So the hooks would be needed in your router page to disable the portal, or v-if the content of the portal out of document.

**Comment by LinusBorg** [comment]
@tmorehouse I thought along those lines as well, but in his codepen, the route view component that contains the `<portal>` is *not* in a `<keep-alive>`, so the portal should be properly destroyed when navigating away - and that seems to happen in the codesandbox he shared.

So for me the sandbox works fine, can't really process in any direction.

**Comment by tmorehouse** [comment]
Hmmm interesting, and bizarre

**Comment by Eggwise** [comment]
Guys, thanks.

I'll try to make a github repo where i can demonstrate the problem when i have the time.
Ill close my comment for now and let you know when i have it done.

Thanks fo your quick response and help!
