### ISSUE TITLE
2.*: Simply slots usage(requires(Vue 2.6)

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#181]
In Vue 2.6, normal slots and scoped slots are both really scoped slots under the hood, and a normal default slot is also accessible as the default scoped slot.

We can therefore optimize here: https://github.com/LinusBorg/portal-vue/blob/next/src/components/portal-target.tsx#L80-L82

A side effect might be that portal-vue 2.0 will require Vue >=2.6 - not sure if that's worth it?

**Comment by tmorehouse** [comment]
It could be optimized for Vue 2.6.x, but will work as is in V2.6 or lowere.

**Comment by LinusBorg** [comment]
Not if I choose to always call `$scopedSlots.default()`. 

 Already thinking I'm nitpicking here  and should drop it.

**Comment by tmorehouse** [comment]
The way the code is today, check for both scoped and plain slots will work with both 2.6 and 2.5 and lower.

**Comment by LinusBorg** [comment]
Yes. Which is what i wanted to change.

**Comment by LinusBorg** [comment]
Closing this as it seems like an unnecessary optimization
