### ISSUE TITLE
targetEl with multiple mode support

### ISSUE THREAD

**Issue by bgondy** [LinusBorg/portal-vue#186]
Is rendering multiple elements in an element outside of the Vue app (via the `targetEl` prop) supported ?

If yes, how to do so ? I didn't find any information about this in the documentation.

**Comment by LinusBorg** [comment]
It will be in 2.0 with `MountingPortal`, check out the docs for the beta, it's in the README. 

Basically you just send to the same `to` name and element and set the `multiple` prop.
