### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#2]
- [ ] Setup Testcafé

Test Cases will be all examples in `/examples`

Tests:
- [ ] Events in portal'ed content correctly execute in source components
- [ ] Hiding source removes content
- [ ] Hiding and re-creating target makes content reappear
- [ ] Switching `name` in Target gets content from new source
- [ ] Switching `to` in source removes content from old Target and renders in new target
- [ ] Switcheroo between 2 portals using the same target does not override each other (See #3).
- [ ] Mouting outside of the DOM works
- [ ] removing source that used `mountTarget` removes target

**Comment by miherlosev** [comment]
To avoid eslint comments  like this `/ global fixture test /`
you can use the [eslint-plugin-testcafe](https://www.npmjs.com/package/eslint-plugin-testcafe)

**Comment by LinusBorg** [comment]
Won'T add those for 1.0.0 - unit tests and visual tests have covered everything so far.
