### ISSUE TITLE
Cannot read property 'getters' of undefined

### ISSUE THREAD

**Issue by kyusupov33** [LinusBorg/portal-vue#202]
When I use <MountingPortal> to render a component outside of the main Vue component, this.$store.getters is not available.

**Comment by LinusBorg** [comment]
What version are you on?

I just (supposedly) fixed this yesterday with 2.1.1

**Comment by kyusupov33** [comment]
@LinusBorg oh thanks, i up to 2.1.1 from 2.0 and its solve my problem :)
