### ISSUE TITLE
[feature request]: add new prop `targetSlim` to MountingPortal

### ISSUE THREAD

**Issue by tmorehouse** [LinusBorg/portal-vue#203]
`MountingPortal` allows for several props to be passed to the dynamically generated `PortalTarget`, but it is missing the ability to pass the `slim` property.

It would be nice to have a new prop `target-slim` on `MountingPortal` which is passed onto the generated `PortalTarget` as the `slim` prop.

**Comment by LinusBorg** [comment]
Hm, that must indeed have slipped through, wasn't an intended omission.
