### ISSUE TITLE
"Target nav-more already exists" when using vue router.

### ISSUE THREAD

**Issue by pmochine** [LinusBorg/portal-vue#209]
_Error on portal-vue@2.1.3_

Hey, I didn't have this problem with < 2.x.x, however now I get the log warning:

    [portal-vue]: Target nav-more already exists

I know about the issue [204](https://github.com/LinusBorg/portal-vue/issues/204), however since this is not an SSR issue, more an SPA issue I want to open this up again.

I have a page with `<router-view />`, inside this view I have multiple portals with:

 ```
 //a component used multiple times
<portal v-if="! visible" to="nav-more" :order="order">some content</portal>
```

```
//a drop down menu component
<drop-down id="nav-more">
    <portal-target name="nav-more" multiple />
    <slot />
</drop-down>
```

Now when I push another page with `$router.push`. I get the warning.

I'm not really sure why, but my guess it must be because of the route-view that loads the whole page from scratch?

**Comment by LinusBorg** [comment]
You couldn't have this issue in <2 since we didn't check for duplicate targets before.

> I'm not really sure why, but my guess it must be because of the route-view that loads the whole page from scratch?

I don't think so. This can happen for two reasons: 

1. You unintentionally have two active `<portal-target>` components with the same name at the same time in your page. This is what the error is supposed to warn about
2. Some old `<portal-target>` doesn't get properly destroyed for some reason, maybe a memory leak in your app, and so it persists active in memory even though it's not used, and leads to this error when you create a second instance of a target with that name.

What exactly does the drop-down component do with the portal-target?

**Comment by pmochine** [comment]
@LinusBorg Merke gerade, dass ich mit dir auch auf Deutsch schreiben könnte :P Danke für die schnelle Antwort.

So I tried your idea to extract it from the `<drop-down>` component. The "warning" is gone. However, I found out it's not because of the component itself.  `<drop-down>` is just a wrapper with a slot for showing a dropdown button + the content of the popper. 

When I tested it, I moved the `<portal-target>` one level up, just to test is fast:

```
<template>
    <div>
        <portal-target name="nav-more" multiple />
    </div>
</template>
```

This worked fine, but when I started to add the previous HTML tags back, it showed me the warning log again:

```
<template>
    <div class="some-css-classes" :key="'more-'+food.id">
        <portal-target name="nav-more" multiple />
    </div>
</template>
```

So the issue lies with :key. It's weird because I'm using it to force Vue to refresh the content of the dropdown when the id of food is changing.

I'm gonna try to build a fiddle for you

**Comment by pmochine** [comment]
@LinusBorg here is the fiddle: https://codesandbox.io/s/x952lolp7p

Click on "Click on me" and the URL is going to change. However, for each change, I get the console warning. (There is even a console tab on this page, didn't know it before)

**Comment by tmorehouse** [comment]
It might be that Vue is creating the new `<portal-target>` with the same name before it destroys teh old `<portal-target>`

Maybe if you set a key on the portal-target so either Vue does or doesn't re-use it.

**Comment by LinusBorg** [comment]
That's indeed a possibility. If so that would be... bad? 

Maybe pushing the internal register call to the next tick could solve it...

**Comment by LinusBorg** [comment]
Seems indeed to be the case. I'll try a fix later.

**Comment by pmochine** [comment]
Thank you for fixing it 🎉 (I was worried that there is some bug in my side :P )

**Comment by LinusBorg** [comment]
Thank me when this is actually tested and published ^^

For now, you can simply disable the check as explained in #204

**Comment by pmochine** [comment]
@LinusBorg aber jetzt: danke 😛

**Comment by pstephan9** [comment]
> That's indeed a possibility. If so that would be... bad?
> 
> Maybe pushing the internal register call to the next tick could solve it...
> 
> I might have some time to take a closer look tomorrow

I don't know how to say this: it's GREAT to be able to have several portal targets under one name. Put a smiley in 5 spots at the same time! Remove the warning!
