### ISSUE TITLE
Use-Case: How to use in monorepo

### ISSUE THREAD

**Issue by johannes-z** [LinusBorg/portal-vue#210]
I have a lerna monorepo, one of the packages is the main app, the other package is just a basic HOC library (it's actually a widget).

In the widget package I want to use the `Portal`, and in the main app I want to use `PortalTarget`. I'm using it like this:

## Widget package:

``` vue
<template>
  <div>
    <portal to="destination">
      <p>
        asdf
      </p>
    </portal>
  </div>
</template>

<script>
import { Portal } from 'portal-vue'
</script>
```

## Main app:

```vue 
<template>
  <div>
    <portal-target name="destination" />
  </div>
</template>

<script>
import { PortalTarget } from 'portal-vue'
</script>
```

## The Problem

The slot content of the `Portal` does not render in the `PortalTarget`. All that's renderd is `<div class="vue-portal-target"></div>`.

Am I doing something wrong?

**Comment by tmorehouse** [comment]
In your script sections you are not letting Vue that you are using the components.

```html
<script>
import Vue from 'vue'
import { Portal } from 'portal-vue'
Vue.use('Portal', Portal)
</script>
```

or

```html
<script>
import { Portal } from 'portal-vue'
export default {
  components: { Portal }
}
</script>
```

**Comment by KennanChan** [comment]
Is there a solution for this issue?
