### ISSUE TITLE
Scoped styles?

### ISSUE THREAD

**Issue by sp00x** [LinusBorg/portal-vue#213]
I noticed that if the content inside my portal uses scoped styles, I had to do this to get it working properly:

```
<template>
  ...
    <portal to="navbar-extra">
      <div class="navbar" v-bind="{ [ $options._scopeId]: '' }">
          ... my stuff that won't be styled unless I apply the v-bind fix ...
      </div>
    </portal>
  ...
</template>

<style scoped>
.navbar {
  /* stuff here */
}
</style>
```

Is there some more elegant, intended way of doing this that I've missed out on in the docs, or is this just the approach that has to be used?

**Comment by LinusBorg** [comment]
Never had a problem like this, so I'm a bit stumped. Could you provide an example e.g.  on code sandbox

**Comment by sp00x** [comment]
Hm, I tried recreating it now in a codesandbox project, but of course I can't reproduce it. I will give it a few more shots and have a look at my own project to see if I can understand what's going on there..

**Comment by sp00x** [comment]
It _appears_ as if this was just a case of `vue serve` hot-reloading fooling me, as when I hard-reloaded the entire page it seems to work fine without manually injecting the scope data-attribute.. I'm quite sure I did this yesterday also, but when you're troubleshooting you tend to try all sorts of stuff and it all ends up kinda blurry :)
