### ISSUE TITLE
Ability to "require" a target to exist

### ISSUE THREAD

**Issue by Duarte-Dias** [LinusBorg/portal-vue#214]
I'm using portal-vue for creating components that you plug into a view. and in the same view declare the portal targets position. Here's an example:
```html
<template>
  <div>
     <MyIntegration /> <!-- Has a MyIntegration__listItem portal inside -->
     <ul>
       <li> List Item </li>
       <li> List Item </li>
       <li> <PortalTarget name="MyIntegration__listItem" />
     </ul>
  </div>
</template>
```

Various components will use this integration, and I want to enforce that the components use the portals if they use the integration

My proposed api is a "required" prop that can be set on Portals

**Comment by LinusBorg** [comment]
I'm not sure I understand what you are asking for. Are you asking for a way to raise an error from a portal (which you use in your component) if the user of your component hasn't provided a target of a specific name?

**Comment by Duarte-Dias** [comment]
Exactly

**Comment by LinusBorg** [comment]
Can you can use `Wormhole.hasTarget()`  for your usecase?

https://portal-vue.linusb.org/api/wormhole.html#hastarget

**Comment by Duarte-Dias** [comment]
Yes, thanks! The wormhole API is awesome :)
