### ISSUE TITLE
Turn the "Documentation" page into a single view

### ISSUE THREAD

**Issue by Duarte-Dias** [LinusBorg/portal-vue#217]
I recently had an issue that could be easily solved if I knew about the Wormhole API. I didn't find this API because the "Documentation" section in the docs is a dropdown menu.

Even if the dropdown menu is kept. I think it would be more user friendly to make a page with all the documentation content instead of having different pages. These pages aren't that big at all and there is no need for the separation.

Thank you for the amazing work you did on this package,
Duarte

**Comment by LinusBorg** [comment]
Thanks for the suggestion. I do see that it would be a slight improvment, but don't think I'll have the capacity to do this anytime soon.
