### ISSUE TITLE
Error if portal content is not defined

### ISSUE THREAD

**Issue by Akryum** [LinusBorg/portal-vue#22]
The render function crash if there is no content passed to the portal, at this line: [portal.vue#L101](https://github.com/LinusBorg/portal-vue/blob/develop/src/components/portal.vue#L101)

Example: 

```javascript
render (h) {
  return h('portal', {
    attrs: {
      to: 'modals',
    },
  }, store.getters[ACTIVE] ? [ h(modals[store.getters[OPERATION]]) ] : null)
},
```

**Comment by LinusBorg** [comment]
Thanks, will fix that soon.
