### ISSUE TITLE
[bug] scopedSlots do not rerender

### ISSUE THREAD

**Issue by SeregPie** [LinusBorg/portal-vue#222]
DOM identical components inside the portal do not rerender their scoped slots.

example
https://codepen.io/SeregPie/pen/vwxQrb
Try switching between the views. The content inside the scoped slot does not rerender.

Remove the `v-slot="props"` and it will magically work properly.

Maybe its a problem with Vue itself.

**Comment by LinusBorg** [comment]
Thanks for reporting this.

From a first look, it seems related to Vue re-using component instances. 

It doesn't happen when I remove the surrounding portal, so seems caused by the portal.

Could be tricky :(

A workaround is to apply a key the component providing the slot props.

**Comment by LinusBorg** [comment]
So I took a closer look a this. It's related to how Vue optimizes scoped slots when using the new `v-slot` syntax.

Simplified, it goes like this:

Vue statically analyses the parent elements in the template for any loops (v-for), conditionals (v-if) etc. and if none are found, it assumes that it can safely cache the scoped slot function that it passes to the child.

This usually works great, but in the constellation that's demonstrated above, we (by using the portal) essentially switch out the scoped slot function without Vue noticing, so it thinks it can keep the cached version of it, while in reality, it shouldn't/can't.

Right now I'm not sure if this is 100% related to what the portal does or if it's a more general caveat or even bug in the caching that Vue employs here (we alrady have fixed a couple of bugs related to that in Vue `2.6.0 to 2.6.10`), I'll discuss this with the team.

For now, it seems we have to document this as a caveat.

Workarounds: 

a). Add a unique `key` to components providing the slot, as menioned in my previous comment.

https://codepen.io/LinusBorg/pen/LoOpLp

Downside: This destroys and re-creates the component in question.

b) Add a `v-if="true"` to prevent the caching:

https://codepen.io/LinusBorg/pen/PvOPKK

Downside: well, it's a hack, really.

c) use old scoped slot syntax:

https://codepen.io/LinusBorg/pen/dEZYVM

Downside: Works fine, and will continue to work fine in Vue 2, but is deprecated and will be removed in Vue 3, so people will try and (want to) use the new API, usually

**Comment by SeregPie** [comment]
Ah. Ok. Thank you. I wonder how it will work in Vue 3.0.

**Comment by LinusBorg** [comment]
Well, Vue 3.0 will support (basic) Portals natively, so Problems like this one will (have to be) solved in core.

Portal-Vue will then adapt the new official Portals and maybe sugarcoat it with some goodies that the basic implementation in core won't come with.

But it's too early to go into details, too many moving parts right now.

**Comment by lukaszmakuch** [comment]
I understood this problem quicker thanks to this thread. Thanks! 🙏

**In my testing render functions turned out to be the only reliable way to get scoped slots to work in portals.** I described my findings in [a blog post on portals and scoped slots](https://coder.earth/post/portals-in-vue2-dont-work-with-slots-props-from-scoped-slots).
