### ISSUE TITLE
unpredictable portal result when using v-if

### ISSUE THREAD

**Issue by y-nk** [LinusBorg/portal-vue#227]
Demo: https://jsfiddle.net/y_nk/52ytmvqx/

Step to reproduce : 

1. Load the demo : actual state is `{ A: true, B: true }`, displays : `bar`
2. Untick the first checkbox : state is `{ A: false, B: true }`, displays: `bar`
3. Tick back the first checkbox : state is `{ A: true, B: true }`, displays: `foo`

I'm starting to understand the reasons why it is like that (cf link below), and yes, there's a v-if on those portals (which could be arguable) but overall I think this is still a valid issue.

PS: probably linked to https://github.com/vuejs/vue/issues/10070

**Comment by LinusBorg** [comment]
This is not related to Vue. the Portal content is rendered in the order that it's being received, and if the portal-target doesn't have `mulitple` set, it essentially behaves like a FIFO queue of length 1.

* So at first, the first portal sends its content, then the second one does, so `bar` is shown
* then the first portal removes its content, so `bar` is still shown
* then the first portal sends its content again, overriding the second portal's content, so now the `foo` is shown.

I don't see much chance to do anything about this, as portal-vue would have know about occurence order of both portals in the parent template in order to behave like you want it to, and that's not really possible.

A fix/workaround would be to use a discrete `order`:

https://jsfiddle.net/Linusborg/1kzcw630/

**Comment by LinusBorg** [comment]
So after thinking about it some more, we could consider to keep the first portal's place in the queue and just mark it as "dead" or something, instead of removing it.

Then if the portal sends content again, we could use that place again, keeping original order.

that would have to be implemented as a separate feature, activated with a prop, to keep backwards compatibility.

**Comment by y-nk** [comment]
@LinusBorg thanks for your feedback. i wonder how we could identify the first "dead" one and the first new one as the same instance since they'll probably be 2 separates vm?

**Comment by y-nk** [comment]
@LinusBorg I've been thinking about what you said... Could you please explain how it is not related to the ticket i mentioned ?

--- 

Even with `multiple`, it's still a FIFO~ sending all rendered content to the portal-target... When ticking 1 then 2, result will be `foobar`, but when ticking 2 then 1, result will be `barfoo` (right?)

I've been adding few lines to the original demo to express that in a more concise manner (just sit back and watch the console 😄) : https://jsfiddle.net/y_nk/xns2gheL/

From the log, you can see that : 

```
[render] uid: #4 (1559015364480)
--- [uid]: 4 foo

[render] uid: #6 (1559015366489)
[render] uid: #4 (1559015366493)
--- [uid]: 4 foo [uid]: 6 bar

[render] uid: #8 (1559015370505)
--- [uid]: 8 bar

[render] uid: #10 (1559015372517)
[render] uid: #8 (1559015372519)
--- [uid]: 8 bar [uid]: 10 foo

[render] uid: #12 (1559015376534)
[render] uid: #14 (1559015376535)
--- [uid]: 12 foo [uid]: 14 bar
```

- The first test case adds `foo`, then `bar`. We can see that the test works great even if the `bar` vm (`#6`) gets rendered before : rendering order is #6, then #4, so if it was just a standard FIFO, i guess the output should have been `barfoo`.

- The second test case adds `bar`, then `foo`. It also works smae as the first test case, since we can see the rendering order and visual output is consistent.

... **and this is exactly what i wanted to show in this issue** ... it works logically as a FIFO as you explained it (i understand the logic, truely), but it doesn't respect the order as written in the template.


_I added a last test case to add `foo` and `bar` together to show that even if the output is the same, the rendering order differs and for such it's not a reliable information to fix that issue._

--- 

If i understand right, it's related to the fact that you cannot relay on order of operations to make sure the 1st "foo" portal will be render before "bar" portal, and that's why you added the `order` property to fix it.

_In that sense I think that it is related to Vue, don't you think?_

**Comment by LinusBorg** [comment]
> Even with multiple, it's still a FIFO

Yep. it's just no longer "a FIFO *of length 1*".

And that's expected given my current implementation. PortalVue has a cache where it collects content from `<portal>` components for `<portal-target>` components to fetch it,

That cache is a simple array, and each time a *new* portal sends content, I `.push()` to this array. If an active portal just sends new content, I don't push. but instead update the existing cache item in the array at its current position.

And the `<portal-target>` renders items in the order that the cache provides them.

So the effect is 100% related to my implementation and definitely *not* related to Vue.

**Comment by y-nk** [comment]
> That cache is a simple array, and each time a new portal sends content, I .push() to this array. If an active portal just sends new content, I don't push. but instead update the existing cache item in the array at its current position. And the <portal-target> renders items in the order that the cache provides them.

got it.

> In order to make this work better, I would have to (provide the option to) never actually delete an item (=specific portal's content) and instead mark it as "inactive", so that I can reactivate and replace its content in the old position in the cache array if the source portal becomes active again.

I still don't understand how you can follow the template's order or even match "inactive" portal without a data of reference (a unique name to follow through all the renders?) but i guess you know already how to do it.

thanks a lot for taking the time to answer/explain.

**Comment by LinusBorg** [comment]
Portals can have a `name` prop (which defaults to a random string).

With a stable name you have a stable I'd for the source.

**Comment by y-nk** [comment]
@LinusBorg i was expecting such a way to identify them :) thanks again.

**Comment by LinusBorg** [comment]
Closing this in favor of #230
