### ISSUE TITLE
Portal inside conditional wrapper

### ISSUE THREAD

**Issue by mitar** [LinusBorg/portal-vue#229]
After some investigation, I discovered that what I am missing is some kind of "intent to transmit to the portal" flag which would then allow me to conditionally render the portal.

I am trying to use portal with [Vuetify toolbar](https://vuetifyjs.com/en/components/toolbars), namely into the extended space provided by the toolbar. The idea is that other component could send content into that extended space. The problem is that if no other component is sending content, the extended space itself should not be rendered.

So I would need something like:

```vue
<v-toolbar
  app
  absolute
>
  <v-toolbar-items>
    ...
  </v-toolbar-items>
  <template
    v-if="isToolbarPortalActive"
    slot="extension"
  >
    <portal-target name="toolbar" />
  </template>
</v-toolbar>
```

The problem is that if `isToolbarPortalActive` is set to `false`, `portal-target` is not rendered at all. So I cannot use its event handler to detect that content has been send to the portal target to flip the `isToolbarPortalActive`.

So `isToolbarPortalActive` should behave more like that "there is intent to render content", so once there is intent, `isToolbarPortalActive` would be set to `true`, `portal-target` would be rendered, and then content inside it.

Is something like that already possible? Am I missing something?

**Comment by y-nk** [comment]
1. i believe you should add `multiple` to your portal if your intent is to [add multiple sources at once](https://portal-vue.linusb.org/api/portal-target.html#multiple) in it.

2. you can leverage the wormhole api for your v-if with [hasContentFor](https://portal-vue.linusb.org/api/wormhole.html#hascontentfor)

**Comment by mitar** [comment]
> i believe you should add multiple to your portal if your intent is to add multiple sources at once in it.

I don't. :-) But thanks.

> you can probably use the wormhole api for your v-if with hasContentFor.

This was exactly what I was looking for. Awesome. This made it work.
