### ISSUE TITLE
docs: 404 on /guide/ssr

### ISSUE THREAD

**Issue by pimlie** [LinusBorg/portal-vue#232]
This link doesnt work when you browse to it directly: https://portal-vue.linusb.org/guide/SSR.html (which redirects to https://portal-vue.linusb.org/guide/ssr/)

Seems to be a case-sensitivity issue, https://portal-vue.linusb.org/guide/ssr.html does work. Might be an issue with the webserver, because when I locally run `docs:dev` everything does work

**Comment by LinusBorg** [comment]
Thanks! should be easy enough to fix.

**Comment by LinusBorg** [comment]
fixed
