### ISSUE TITLE
Child component emitting event but parent can't see it

### ISSUE THREAD

**Issue by ladobarnovi** [LinusBorg/portal-vue#237]
I have a case like this

`
<portal to="modal-portal">
  <ModalComponent @close=closeModal()/>
</portal>
`

The problem is that ModalComponent emits "close" event but apparently parent component can't see it and it does not trigger closeModal() function. Is it supposed to be this way?

**Comment by LinusBorg** [comment]
This usually works fine. Please provide a way to reproduce the problem.

**Comment by ladobarnovi** [comment]
I figured it out, everything works as expected. Sorry, my bad, I will not close the issue.
