### ISSUE TITLE
Add portal directive or be abstracted

### ISSUE THREAD

**Issue by miljan-aleksic** [LinusBorg/portal-vue#24]
@LinusBorg, thank you for this awesome plugin!

I would like to suggest making the portal component abstract or be a directive. Is kind of unexpected that `this.$parent` in ported components is not the component they were ported from. In my opinion, the portal should be just doing what it says and not getting in the way.

**Comment by LinusBorg** [comment]
Hey @miljan-aleksic,

thanks for pointing this out. I will think about this and play around with the options we have.

**Comment by LinusBorg** [comment]
So I tested this as an abstract component, and it works well. the downside is that you don't see the components in the devtools anymore.

So I will try to get a workaround for that as well.

**Comment by miljan-aleksic** [comment]
Why is that? Transition components are visible beside it being abstract.

**Comment by LinusBorg** [comment]
The components in the slot are visible - the `<portal>` and `<portal-target>`ones are not.

That's not a real dealbreaker, but I would prefer if they were visible. But not sure yet weither both are possible together.

**Comment by LinusBorg** [comment]
I think I will publish the next version with `abstract: true`.

Haven't found a way to make the portal components visible in the devtools then, but that's not a real problem I would say.
