### ISSUE TITLE
Adding an iframe along with portal-vue causes Vue to no longer function correctly

### ISSUE THREAD

**Issue by javangriff** [LinusBorg/portal-vue#241]
My apologies if I am missing something here, but there appears to be an issue with *portal-vue* when an `<iframe>` is added to the document in Sarafi.

In this example (https://codepen.io/javogriff/full/ymByBz), when the button is clicked Safari the `clickHandler` method is fired and the `itemActive` attribute is updated, however, the document is no longer updated as it should with the relevant classes being applied to the element. If either the `<iframe>` (https://codepen.io/javogriff/full/qeWzMY) or *portal-vue* (https://codepen.io/javogriff/full/YmKoJR is removed from the document, everything functions as expected.

Tested in Safari Version 12.1.1 (14607.2.6.1.1) and also IOS Safari.

**Comment by engram-design** [comment]
Any update on this, or why it might be occurring? Seeing this as well, as soon as an iframe is embedded on the page variables become non-reactive for some reason.

**Comment by LinusBorg** [comment]
I have zero idea what is going on here and don't think that the presence of an iframe could in any way influence the code of portal-vue itself.

Looks rather like a weird Safari bug.

I'll close this as a browser quirk
