### ISSUE TITLE
Is the default value of disabled prop incorrect?

### ISSUE THREAD

**Issue by LovelySmallCat** [LinusBorg/portal-vue#244]
The default value displayed by the API is false：
<img width="379" alt="1" src="https://user-images.githubusercontent.com/29880393/61760577-984d1e00-adfe-11e9-88c6-0cc6cfc1a837.png">

But according to my test, the result is just the opposite.：
<img width="478" alt="2" src="https://user-images.githubusercontent.com/29880393/61760715-fe39a580-adfe-11e9-9f14-a84f0418bbb4.png">

Result：
<img width="1306" alt="3" src="https://user-images.githubusercontent.com/29880393/61760748-20cbbe80-adff-11e9-9c61-55d052bb5013.png">
Content still resides in portal components,This is different from what the API expects!

My version：^2.1.5

Looking forward to receiving a reply!

**Comment by LinusBorg** [comment]
adding an attribute/prop without a value is the same as setting it to true. This is how props behave in Vue (and how attributes behave in HTML itsle, e.g. `hidden` or `checked`

**Comment by LovelySmallCat** [comment]
> 添加没有值的属性/ prop与将其设置为true相同。这就是道具在Vue中的行为方式（以及属性在HTML本身中的行为方式，例如`hidden`或`checked`）。
> 
> 所以这是按预期工作的。

I haven't found this description in the Vue API. Where can I see the detailed description? Can you give me a url? Thank you very much, uncle!

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean

**Comment by LovelySmallCat** [comment]
> https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean

Thank you, I have learned!
