### ISSUE TITLE
2.1.5 fix for `force = true` appears to be missing from dist files

### ISSUE THREAD

**Issue by Aaron-Pool** [LinusBorg/portal-vue#249]
it looks like this [commit, which was supposed to be released in 2.1.5](https://github.com/LinusBorg/portal-vue/pull/216/files#diff-5ac4880c2e868424cea763ae8d13078fR57), didn't actually make it into the deployed build, for some reason. As you can see [here](https://github.com/LinusBorg/portal-vue/blob/develop/dist/portal-vue.common.js#L141) the distributed file is missing this change.

**Comment by LinusBorg** [comment]
Should be easy enough to fix with a quick new build & publish, will do that tomorrow evening.

**Comment by Aaron-Pool** [comment]
@LinusBorg Did this redeploy ever happen?

**Comment by LinusBorg** [comment]
Not yet. Life happened in between.

Will start another attempt tonight.

**Comment by Aaron-Pool** [comment]
No problem, no rush! Just wanted to make sure it hadn't slipped through the cracks. Thanks for the quick response!

**Comment by LinusBorg** [comment]
closed with release 2.1.6
