### ISSUE TITLE
Support for vue-native.

### ISSUE THREAD

**Issue by frankperez87** [LinusBorg/portal-vue#250]
When trying to use this package within a **vue-native** application, I'm receiving the following error

```bash
Unable to resolve "vue" from "node_modules/portal-vue/dist/portal-vue.common.js"
```
Vue native applications seem to import their own version of **vue** 
from a package called **vue-native-core**.

Is it possible to have this package reference **vue-native-core** instead of **vue**? Or is there any other workaround that anyone can suggest?

**Comment by tmorehouse** [comment]
You may need to set up an alias of `'vue'` to point to the `vue-native-core` package in your webpack config:

```js
module.exports = {
  // ...
  resolve: {
    alias: {
      'vue$': 'vue-native-core'
    }
  }
}
```

https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by frankperez87** [comment]
Looks like **vue-native** uses the Metro bundler. Do you know off hand if theres any alternative outside of the *webpack* solution?

**Comment by tmorehouse** [comment]
Not sure about Metro, but Vue provides similar examples for Parcel, Rollup and browserfy https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by LinusBorg** [comment]
I won't be able to solve this in portal-vue, metro has to be properly set up to import the right version of Vue.

This problem will exist with any Vue plugin that itself imports Vue, so it's not specific to this library here.
