### ISSUE TITLE
Moving elements in complex ways

### ISSUE THREAD

**Issue by yansenlei** [LinusBorg/portal-vue#253]
I have a tricky problem now. I need to drag the component multiple times and save the original state. Can this library be supported? Looking forward to your reply.

![demo](https://user-images.githubusercontent.com/23315895/64192832-244a6f00-ceae-11e9-8a16-974b6a5b0590.gif)

**Comment by LinusBorg** [comment]
Drag& drop isn't really within the scope of this library. Where exactly do you see the use case?

**Comment by yansenlei** [comment]
This is my case. I want to refer to your library and want to determine if the component's internal state and life cycle will be affected after moving the component multiple times.

**Comment by LinusBorg** [comment]
Moving components will destroy and re-create them.

**Comment by yansenlei** [comment]
Thank you for your reply.
Is there any way to keep the state of the component from being destroyed? What are your ideas for doing this?

**Comment by LinusBorg** [comment]
No, there is no way in the context of this library.
