### ISSUE TITLE
Feature Request: option to define what tag the portal target uses

### ISSUE THREAD

**Issue by JonathanLouw** [LinusBorg/portal-vue#261]
Could we have the option to decide what tag is used for the target? For my case I want to portal a status to the end of a tab via an icon however the root tag for the target is a div. This isn't too big of an issue as I can just apply a style to fix it but could be handy for other cases.

So for example

```html
<portal-target tag="span" name="projectTabStatus">
    <i class="fa fa-check" v-if="status == 'completed'"></i>
    <i class="fa fa-hourglass-half" v-else-if="status == 'pending'"></i>
</portal-target>
```

Will result in this
```html
<span>
    <i class="fa fa-check"></i>
</span>
```

Instead of how it currently renders using divs by default:
```html
<div>
    <i class="fa fa-check"></i>
</div>
```

**Comment by LinusBorg** [comment]
Have another look at the docs, that's already supported.
