### ISSUE TITLE
Using a deep selector to apply styles from parent component to child component containing a portal

### ISSUE THREAD

**Issue by icoumans** [LinusBorg/portal-vue#263]
I have created a `Page` component and a `Dialog` component. On the `Page` component I add a `Dialog`, and want to apply styles to it. The `Dialog` component uses `portal-vue` to move the entire content out of the page (for a modal dialog).

I've managed to reproduce this in [a simple Code Sandbox here](https://codesandbox.io/s/wispy-hooks-bs0m5?fontsize=14).

From `HomePage.vue` I expect to be able to style the `.specialtext` class green (using a deep selector). This works when I don't use a portal. However, using a portal will not apply the style.

**Edit after closing the issue:**
As I thought, this is issue is more of a working-as-intended. A workaround by @tmorehouse was posted below:

> Although there is a "trick" you can do to get the scope data attribute on your portalled content root element though.
> 
> If your portal source is in your component, you can get the scope attribute name via:
> 
> ```js
> export default {
>   methods: {
>     getScopeAttrs() {
>       // Get the scope attribute name (undefined if none)
>       const scopeAttr = this.$parent.$options._scopeId
>       return scopeAttr ? { [scopeAttr]: '' } : {}
>     }
>   }
> }
> ```
> 
> And when rendering your portal content root element, add the attribute:
> 
> ```
> <template>
>   <portal ....>
>     
>     <div v-bind="getScopeAttrs()">
>     </div>
>   </portal>
> </template>
> ```
> 
> We've done this in BootstrapVue to allow scoped deep selectors work for Modals, Toasts, etc.

**Comment by tmorehouse** [comment]
Scoped styles (even with the deep selector) will not typically work, as the content's parent changes from your component to the portal target, and the style scoping (the `data-v-xxxx` attribute) is pulled from the parent's context.

**Comment by tmorehouse** [comment]
Although there is a "trick" you can do to get the scope data attribute on your portalled content root element though.

If your portal source is in your component, you can get the scope attribute name via:

```js
export default {
  methods: {
    getScopeAttrs() {
      // Get the scope attribute name (undefined if none)
      const scopeAttr = this.$parent.$options._scopeId
      return scopeAttr ? { [scopeAttr]: '' } : {}
    }
  }
}
```

And when rendering your portal content root element, add the attribute:

```html
<template>
  <portal ....>
    <!-- root element or component that you are portalling -->
    <div v-bind="getScopeAttrs()">
    </div>
  </portal>
</template>
```

We've done this in BootstrapVue to allow scoped deep selectors work for Modals, Toasts, etc.

**Comment by icoumans** [comment]
> Scoped styles (even with the deep selector) will not typically work, as the content's parent changes from your component to the portal target, and the style scoping (the `data-v-xxxx` attribute) is pulled from the parent's context.

I figured as much. On the one hand I realized my issue wasn't really an issue, but mostly a "working-as-intended". But I was hoping for a workaround.

> Although there is a "trick"...

Thank you very much for this workaround, it works like a charm. I was not aware of the possibility to "inherit" the data-v-xxx attribute like this.

> ```js
> export default {
>   methods: {
>     getScopeAttrs() {
>       // Get the scope attribute name (undefined if none)
>       const scopeAttr = this.$parent.$options._scopeId
>       return = scopeAttr ? { [scopeAttr]: '' } : {}
>     }
>   }
> }
> ```

I am assuming the equals sign after return is a typo?

**Comment by tmorehouse** [comment]
Yep... typo... I'll edit my comment above.

**Comment by dcrystalj** [comment]
@icoumans Can you please share your solution. I managed to color it green but only using * css selector and `!important`

https://codesandbox.io/s/charming-morse-xmi5y?file=/src/HomePage.vue
