### ISSUE TITLE
Dynamic children created externally are lost

### ISSUE THREAD

**Issue by HeyThatsLife** [LinusBorg/portal-vue#281]
Hi.

I'm using a lib which adds some children to an element.

I would like to teleport this element. But when I do that, the created children are lost.

Is this a bug? Is there any workaround?

Thank you.

**Comment by LinusBorg** [comment]
Portal-vue moves virtual Dom, not actual Dom.

Since these elements are not part of Vue's virtual DOM representation, they are not moved.

To think about workarounds I would have to see the code in question since I have to understand how and when these elements are created

**Comment by HeyThatsLife** [comment]
It's not really easy to share the code as it spawn across multiple components.

The library used is Twilio Video. It creates a `<video>` and `<audio>` tags in the defined `<div>`. When teleporting the div, audio and video disappear.

But now I understand why (virtual DOM) so thank you. I'll work around the problem by using CSS instead of teleporting the element :)

Thank you.
