### ISSUE TITLE
[bug?]: Target destination already exists when using v-for on portal-target

### ISSUE THREAD

**Issue by grreeenn** [LinusBorg/portal-vue#283]
Not sure if bug or I'm missing something.

In case when I need to render multiple portal targets pointing on the same portal, I get this warning in browser console (times number of elements I've rendered):

> [portal-vue]: Target destination already exists

My code:
```
<portal-target v-for="d of maxValue"
                       name="destination"
                       :key="d"/>

<portal to="destination">
        <div>
            This is my content that I need to render multiple times
        </div>
</portal>
```
Despite the warning, everything renders and functions correctly.

Great package btw, thank you!

**Comment by estaylorco** [comment]
Try putting your `v-for` on `portal`, not `portal-target`.  Then, on `portal-target`, specify the `multiple` property.

**Comment by grreeenn** [comment]
Kind of makes sense. Thanks to your comment I realized that I've misused Portal, and found a way to accomplish what I needed without it. Thank you!
