### ISSUE TITLE
"Target wasn't mounted"

### ISSUE THREAD

**Issue by doncatnip** [LinusBorg/portal-vue#284]
I try to use portal-vue to render vue contents into a FullCalendar resource label. Since FullCalendar has no 'resourceLabelTemplate' where I could specify html markup I use the hook datesRender where I create the target element.

    const datesRender = ({el}) => {
        const resourceLabelEl = el.querySelector('.fc-resource-area.fc-widget-header th.fc-widget-header .fc-cell-text')
        const portalTarget = document.createElement("portal-target")
        portalTarget.id = "calendar-resource-label"
        resourceLabelEl.appendChild(portalTarget)
    }

So every time the calendar is rendered a new 'portal-target' element is created and added to the dom.

Inside the vue component I have the following

    <MountingPortal mount-to="#calendar-resource-label" name="source">                                                 
        <b>bob</b>                                                                                              
    </MountingPortal> 

So I thought <b>bob</b> would appear inside <portal-target> but instead I get "Target wasn't mounted" in the console.

Not sure if I understand the docs correctly 
https://portal-vue.linusb.org/guide/advanced.html#rendering-outside-of-the-vue-app
since there is mention of "PortalTarget" but in the actual example there is only an "aside" element .... but I suppose the actual element type does not matter and it only takes the ID. So I also tried 

    <div id="calendar-resource-label"></div>

Maybe it just doesn't work when the portal-target element is added after vue has been mounted ?

**Comment by doncatnip** [comment]
"Maybe it just doesn't work when the portal-target element is added after vue has been mounted ?"
I am quite sure now that this is the case. I solved my particular issue by creating a new tiny Vue app and mount it into the resource label area.

I am closing this ticket as it would seem to be a feature request that is out of scope.

**Comment by LinusBorg** [comment]
You may want to looks t the `MountngPortal` component, its usecase is precisely to mount a target to an element outside of Vue's control for you.

**Comment by doncatnip** [comment]
I did exactly that as mentioned in the opening post. The problem is that it does not work when the target element is created dynamically after MountingPortal.

**Comment by LinusBorg** [comment]
> The problem is that it does not work when the target element is created dynamically **after** MountingPortal.

yeah, that's correct.

I was a bit confused as you created a custom dom element called 'portal-vue' which is besides the point.
