### ISSUE TITLE
Toggle target content

### ISSUE THREAD

**Issue by forforeach** [LinusBorg/portal-vue#285]
Hi, thank you for the great tool.

I wonder if there is a way to toggle the content of the target element. For example, I would like to implement a modals system, that is injected into a single `portal-target`, but I don't want them to stack each under another, but replace the previous content of the target. Is that possible now? Or is there a workaround for this?

**Comment by LinusBorg** [comment]
That is already possible now, in a way.

If you have a portal-target that **does not** have the `multiple` prop set (which is the default), then it will always show the content that it received last.

So that means that the last `<portal>` that sent content to this target "wins".

If that's not what you are looking for, can you specify how you would like the "toggle" to behave? like, what should trigger it?

**Comment by forforeach** [comment]
Hey, @LinusBorg , thanks for the response.

This is not exactly what I want. Let me try to explain. For example, I'd like to implement a modals system. It is supposed to have one target, that will be placed, for instance immediately after the `body` tag. Each modal instance would be wrapped with `portal` tag that would specify this `portal-target`. When one of the modals is open, it would be displayed in the target, but if the next one is open, it would overide the content of the target. Once closed, the previous modal that is opened would be displayed.

Let me know, if this all makes sense.

**Comment by selfagency** [comment]
Hey @LinusBorg, I'm having a similar issue—I'm using `portal-vue` inside a modal and using a render function to insert the `portal-target` tag into the modal. It works just fine, in terms of my content appearing, but if I switch layout contexts in my Nuxt application, and click the button to open my modal, I start getting `[portal-vue]: Target login-form already exists` errors in multiple. What's odd is, I'm getting the error even if I destroy the `portal-target` element before reinvoking it.

```
      if (this.formInstance) this.formInstance.$destroy()

      this.formInstance = new Vue({
        render(h) {
          return h('portal-target', {
            attrs: {
              name: 'login-form'
            }
          })
        }
      }).$mount('#login')
```

**Comment by LinusBorg** [comment]
@selfagency This doesn't seem to be a similar issue.

I would kindly ask you to open a new issue and provide a reproduction.

**Comment by LinusBorg** [comment]
After thinking about this for a while, I don'T think this makes sense as a feature for this lib, it'ÄS too usecase-specific.

You should handle this in userland, ensuring that only the latest modal ist shown by e.g. tracking some global state that acts as a queue which every modal is aware of.
