### ISSUE TITLE
mounted() firing multiple times

### ISSUE THREAD

**Issue by gorbypark** [LinusBorg/portal-vue#286]
I have a simple component that shows a card, and in that card I have something like 
```vue
mounted() {
  axios.get("https://someurl.com/api").then(response => {
    this.total = response.data[0].total;
  });
}
```
The call the the url seems to be called multiple times, approx every 3 seconds, not just once when the component is mounted.  Is vue-portal re-mounting the component on some sort of loop?

**Comment by LinusBorg** [comment]
No it isn't. I can't say much more without a reproduction.

**Comment by gorbypark** [comment]
Hi, thanks for the quick reply and the awesome project!  Sorry to waste your time, it turned out to be an issue with hot-reloading and restarting the dev server solved my issue.  Thanks again.
