### ISSUE TITLE
When v-show is false, content is still portal-ed to a portal-target

### ISSUE THREAD

**Issue by estaylorco** [LinusBorg/portal-vue#291]
Hello,

When a component is hidden using `v-show`, markup within a `portal` is still portal-ed to a `portal-target`.  With `v-if`, that's not the case.  I understand *in principle* why that is: `v-if` actually removes markup from the DOM; `v-show` does not.

Nevertheless, from a *logical* perspective, it doesn't make sense to me that a component hidden with `v-show` should leak it's portal content.

Is this intended, or are you waiting for maturity in the Intersection API?

I ask because I just spent 2 hours debugging a problem where a portal-ed button was causing an event handler defined in the context of the `portal-target` to fire and get handled there.  When I changed back to `v-if`, the problem went away.  I had this happen a few weeks ago in the context of portalling a Title component (but not realizing what it was until this evening).

**Comment by LinusBorg** [comment]
> Nevertheless, from a logical perspective, it doesn't make sense to me that a component hidden with v-show should leak it's portal content.

I disagree. `v-show` is nothing more than adding/removing CSS. Every component that you put v-show on will behave exactly the same wether its shown or hidden - they will make API requests, emit events, re-render, call lifecycle hooks etc.

I don't see why the Portal should be the sole exception to that rule.

**Comment by estaylorco** [comment]
Right now, in this particular case, I see it as exactly that: an exception to the rule.  `portal-vue` traffics in CSS and markup, in a sense.  So, if the state of the CSS union is `display: none`, `portal-vue` would be behaving *exceptionally* to leak its content.  API requests, events, rendering, etc., are all a matter of *behavior*, not presentation.

Indeed, I wonder, what does it even mean to have a component hidden with `v-show="false"`, only to have that component's portal content display nevertheless?  That's why this was such a puzzling bug for me to squash.  And the effect was rather bizarre.

Would we expect the inner content below to display?
```
<div v-show="false">
   <div>This is hidden now</div>
</div>
```
So, if not, why should we expect the following to be any different?
```
<div v-show="false">
   <portal to="aPortal">
       <div>This shows nevertheless</div>
   </portal>
</div>
```

I'm asking in earnest.  Do you have a use case that you could offer that might help to understand the logic here?

**Comment by tmorehouse** [comment]
`v-show="false"` applies the CSS attribute to the _element_ that it is bound to, and because of DOM hierarchy - controls the visibility of child elements. This is a DOM behavior.

You have to remember exactly what `<portal>` does.... it _changes the DOM hierarchy_ by moving the DOM elements to *another* location in the document.... changing the DOM hierarchy. 

Would you expect the following markup:

```html
  <div style="display: none;">
  </div>
  <div>
     <span>Portalled content</div>
  </div>
```

to visually hide the `<span>` above?  The `<span>` is no longer a DOM child of the first `<div>`.

**Comment by estaylorco** [comment]
@tmorehouse You know, I think I see: Because we're trying *to get out* of the current hierarchy and into another one whose visibility *there* carries the moment.
