### ISSUE TITLE
Vue context is lost when using render function

### ISSUE THREAD

**Issue by selfagency** [LinusBorg/portal-vue#292]
I am working in Nuxt.js and am using a modal plugin called [vue-sweetalert2](https://github.com/avil13/vue-sweetalert2/).

In order to instantiate a Vue component within the modal, I have to pass it a Vue render function. To save myself the humongous headache of hand-writing an AST for my login form, I've opted to use `vue-portal` and just render a `portal-target` component to display my login form component.

Unfortunately, it appears that when using the render function, the context of the Vue instance is lost, and so the various libraries Nuxt appends to the Vue prototype go M.I.A. For example, below you'll notice the line `$i18n: this.$i18n`. This is the Vue-i18n instance in my Nuxt project which I am attempting to reassign to my rendered `portal-target` component. Two lines below that you'll see a `console.log(this)` statement, the result of which shows $i18n properly assigned to `this`. However, if I put a similar `console.log(this)` statement in my `portal` component, `this` shows that $i18n is present on the prototype but `undefined`.

My question is: How do I get the `portal-target` component to pick up Vue-i18n (and preferably the other libraries on the main Vue prototype, like Axios)?

```javascript
    showLogin() {
      let form
      this.displayModal([
        'modal',
        {
          title: 'Login',
          html: '<div id="login"></div>',
          onRender: () => {
            form = new Vue({
              $i18n: this.$i18n,
              render: h => {
                console.log(this)
                return h('portal-target', {
                  props: {
                    name: 'login'
                  }
                })
              }
            }).$mount('#login')
          },
          onDestroy() {
            form.$destroy()
          }
        }
      ])
    },
```

**Comment by selfagency** [comment]
I believe, by the way, that this issue is related to the problem as to why others are getting the `Cannot read property '_t' of undefined` error that appears in other tickets.

**Comment by selfagency** [comment]
I also noticed that I can't debug the children of the `portal` component in the Vue developer tools.

**Comment by tmorehouse** [comment]
You can pass a parent to your portal target:

```js
            form = new Vue({
              parent: this,
              render: h => {
                console.log(this)
                return h('portal-target', {
                  props: {
                    name: 'login'
                  }
                })
              }
```

**Comment by selfagency** [comment]
@tmorehouse hero

**Comment by tmorehouse** [comment]
You can also make its parent the root of your app too:

```js
  parent: this.$root,
```

Which will prevent it from being destroyed on rout changes (if so desired), otherwise it will get destroyed when the `this` instance is destroyed.
