### ISSUE TITLE
How to wait for a tree to be ready

### ISSUE THREAD

**Issue by Garito** [LinusBorg/portal-vue#293]
Hi
I would like to ask if is any way to wait for the portal content to be rendered before move it to the destination

I'm using this component to layout forms and when a page has more than one form and one is filled (so the content of the parent is refreshed, the labels of the other forms disapear

I believe that this is because the portal moves the content to the target before the children is fully updated so loses some parts

Is there a way to prevent this?

Thanks!

**Comment by LinusBorg** [comment]
> I believe that this is because the portal moves the content to the target before the children is fully updated so loses some parts

No, that is likely not the reason, but I have trouble understanding the desscription. Can you come up with a concrete example?

**Comment by Garito** [comment]
Yeah, sorry
I've been following your code and making more test and noticed that is not a matter of your component but of this one: https://github.com/alexjoverm/v-runtime-template
