### ISSUE TITLE
Scoped Style not working with Portal inside a component

### ISSUE THREAD

**Issue by felixx-gempages** [LinusBorg/portal-vue#302]
I'm creating a `<Modal>` component which has `<Portal to="modals">` as the Root element
The `Root.vue` has `<PortalTarget name="modals" multiple>` to hold data from `<Modal>` and ensure that there's no recursive Modal (it mean Modal in Modal, so glitchy).

![image](https://user-images.githubusercontent.com/51904105/82758107-ca5c5180-9e0e-11ea-948b-b08b379bb4fe.png)

But the problem is when I'm using `<Modal>` component in another component, I can't apply any scoped style to elements inside `<Modal>` component. Then I take a look at its DOM but there's no scoped id.

The component that use `<Modal>`

![image](https://user-images.githubusercontent.com/51904105/82758128-eeb82e00-9e0e-11ea-888c-3b8d34f30a8a.png)

Scope not working

![image](https://user-images.githubusercontent.com/51904105/82758167-23c48080-9e0f-11ea-8392-5cbd73179049.png)

Is there any solution for this?

Thanks ^_^

**Comment by tmorehouse** [comment]
Duplicate/related: #263 

See workaround (which may or may not work for your case): https://github.com/LinusBorg/portal-vue/issues/263#issuecomment-549846299
