### ISSUE TITLE
[Question] Two PortalVue instances synchronization

### ISSUE THREAD

**Issue by PeterPorzuczek** [LinusBorg/portal-vue#303]
Is there a way to transfer components between two Vue instances (each with a separate PortalVue instance)? Maybe it is possible to synchronize sources and targets between instances?

The documentation shows that such functionality can be obtained using a mounting-portal, is there any other way?

**Comment by LinusBorg** [comment]
I'm not sure I understand what you mean.

**Comment by PeterPorzuczek** [comment]
I solved a problem using MountingPortal. Thank you for help :)
