### ISSUE TITLE
Can Vue-Portal keep local state alive when switching target ? (Expliciting #113 for switching target)

### ISSUE THREAD

**Issue by thibaut-lo** [LinusBorg/portal-vue#305]
Hi,

Can vue-portal keep the local state alive when I switch between two `portal targets` from the `same portal` (using a `v-bind:to`) ?

#113 suggests that this is not achievable but I am not sure (it is explicitely stated when toggling the `disabled` prop, but not when toggling the `to` prop, the subsequent change in the doc focus on `disabled` as well) ?

(My use case would be to perform send content of the same component (and children components) to different windows location (between dock, grid, and maximized-size panels))

**Comment by LinusBorg** [comment]
No, that's not really achievable in the current architecture. Situation will likely improve in Vue 3.
