### ISSUE TITLE
Portal.targetEl type HTMLElement breaks SSR

### ISSUE THREAD

**Issue by jakepeyser** [LinusBorg/portal-vue#31]
The `portal.targetEl` type of `HTMLElement` causes a `ReferenceError: HTMLElement is not defined` error to be thrown during SSR. As far as I can tell, this plugin supports SSR, but this type breaks that.

A quick fix is to add something like the following to my server:
```
global.HTMLElement = () => {}
```
However, this seems hacky and I would prefer if this was solved at the plugin level if that is at all possible!

**Comment by LinusBorg** [comment]
Hi!

That's alread fixed in the dev branch,I "just" need to update tests and push an new version - putting "just" in quotes because I hardly find time in the coming days, but i'm on it.

Thaks for reporting anyway!
