### ISSUE TITLE
Portal inside KeepAlive can be inactive but still rendered

### ISSUE THREAD

**Issue by albertpratomo** [LinusBorg/portal-vue#320]
Hi, I have a question about `Portal`. When wrapped inside `KeepAlive`, if `show = false`, the `Portal` becomes inactive yet it's still rendered. Thus the `v-if` behavior is not respected..

```
<KeepAlive>
   <Portal v-if="show" to="main-menu">
     Something
   </Portal>
</KeepAlive>
```

**Comment by LinusBorg** [comment]
Yeah that's a nofix. I don't see a way to make this work that's worth the effort.

You should likely use wrap the portal in its own component and use the `(de)activated`hooks in that component to show/hide/disable the portal the way you expect it to.
