### ISSUE TITLE
Portal with no content throws an error

### ISSUE THREAD

**Issue by simplesmiler** [LinusBorg/portal-vue#33]
Repro: https://jsfiddle.net/14dtfh51/20/

**Comment by LinusBorg** [comment]
Thanks!

**Comment by LinusBorg** [comment]
Hm, seems I fixed that already a while ago in `dev`. Can't reproduce this.

TO be sure I will push another beta later this week and test it on your fiddle, before hopefully, finally pushing 1.0.0

**Comment by LinusBorg** [comment]
fixed in develop branch
