### ISSUE TITLE
Usage with ShadowDOM

### ISSUE THREAD

**Issue by jameswragg** [LinusBorg/portal-vue#346]
Hi wondered if anyone has used portal-vue with Custom Elements + ShadowDOM?

I'm trying to create a component that has a modal dialog & appends to body due to z-index positioning but because [vue-loaders shadowMode adds to the shadowRoot](https://vue-loader.vuejs.org/options.html#shadowmode) the modal is unstyled - I'm wondering if I can vue-portal the styles to the body-appended div?

**Comment by LinusBorg** [comment]
I would consider this to be outside of the scope of this package.

You should be able to get the styles from shadowRoot yourself, and append them to the document head if you need this to work.
