### ISSUE TITLE
Portal content does not show up in the devtools sometimes

### ISSUE THREAD

**Issue by simplesmiler** [LinusBorg/portal-vue#35]
Happens when the `target-el` element is placed within an existing Vue instance. I don't know if this is a valid usage though. If it's not, there should probably be a warning when attempted.

Repro: https://gist.github.com/simplesmiler/8b19fd9482be5a6fa06c6a64418f84fd (can't make fiddle, because devtools does not work there).

**Comment by LinusBorg** [comment]
That option was indeed meant to be used outside of the Vue-controlled DOM.

I guess the content does not show up because this manually mounted component is does not appear in the  "parent" component's `$children` collection.

**Comment by simplesmiler** [comment]
I believe the child instance is added to the parent's `$children` automatically, if it is created with the `parent` option.

E.g. `{ parent: closestVueInstance }` over at [portal.vue#L84](https://github.com/LinusBorg/portal-vue/blob/1.0.0-beta.3/src/components/portal.vue#L84), where `closestVueInstance` is the found using the process with `el.__vue__` you described.

**Comment by LinusBorg** [comment]
I'll give this a try!

**Comment by LinusBorg** [comment]
As discussed in #34, we should probably always set the parent to the source portal instance ...

**Comment by LinusBorg** [comment]
fixed in develop branch.
