### ISSUE TITLE
NPM version defaults to 3.x-beta

### ISSUE THREAD

**Issue by didimitrie** [LinusBorg/portal-vue#352]
Hi! just a quick heads up that the npm release version is now at 3.x-beta; getting started with the classic `npm install --save vue-portal` will bork if you're thinking you're going to get a v2 compatible release. 

This noob definitively struggled for half an hour or so to find out what's going on while following the docs! 

PS: I know this is one of those annoying low key not-actual-issue issue that, if agreed, I can try and flop an `@2` throughout the docs and do a PR.

**Comment by LinusBorg** [comment]
Oh snap, that was unintentional, must have screwed that up while publishing.

I want to switch over 3.0 to latest when Vue 3 has done so as well.

I'll see that I repair this situation asap.

**Comment by LinusBorg** [comment]
I have corrected the tags on npm. You should once again get 2.1.7 if you do a normal install from `latest`.

Sorry for the inconvenience.
