### ISSUE TITLE
Not an issue, just praise for the developer

### ISSUE THREAD

**Issue by pocketcolin** [LinusBorg/portal-vue#354]
I just wanted to give a huge shoutout to @LinusBorg for this incredible package. My team was recently finishing up a new web app when we discovered that the way we had setup our modals relied on `position: fixed` which was causing massive headaches on iOS devices ([for those unfamiliar with the issue](https://gist.github.com/avesus/957889b4941239490c6c441adbe32398)). Luckily, `portal-vue` allowed us to very easily and seamlessly teleport all of our modals throughout the app to the top level and, with just a little bit of refactoring, make all of our `fixed` position elements, `absolute`. Now our app is working great in iOS even when the keyboard is open. Thanks for all your work on this, @LinusBorg !

**Comment by EmmyMay** [comment]
Hi, I hope you and your team buy this developer a cup of coffee. Praise is great, but money is greater.
