### ISSUE TITLE
Improve SSR support by skipping during SSR & hydration

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#36]
I thought about a suggestion to skip rendering portal-targets on the server and during re-hydration. Then hydration should work as the DOM should match the vDOM, and we just render the `PortalTarget`'s content a bit later.

Skipping on the client is easy with `this.$isServer`, and I think the best way to check if we are re-hydrating is to check if `this.$root.$el.dataset['server-rendered']`

If that’s present,  we defer rendering the slot content with a `setTimeout(this.$forceUpdate, 0)`, which will re-render the component with the slot content after the rehydration phase is done. We should also set a flag in the target's local data so the next re-render is not deferred again.

**Comment by LinusBorg** [comment]
Wondering if an internal solution is necessary or we shouldn't just recommend to use something like https://github.com/egoist/vue-no-ssr

**Comment by iamdubx** [comment]
Unfortunately, `no-ssr` doesn't work - https://github.com/LinusBorg/portal-vue/issues/65

**Comment by LinusBorg** [comment]
Seems you got it working :)

**Comment by LinusBorg** [comment]
I think I will make this the official way to handle ssr, will amend the docs later.

**Comment by iamdubx** [comment]
Thank you for supporting this great package. I think it would be nice to add `no-ssr` mention in Docs, you are absolutely right. I needed time and help from other person, who point me to this issue, where you advise to use `no-ssr`. Very helpful ecosystem, that plays well together.
