### ISSUE TITLE
Pass data from portal-target parent to portal content

### ISSUE THREAD

**Issue by lgarczyn** [LinusBorg/portal-vue#360]
Hi, and thanks for your work.

My use case is pretty simple, I have a sidebar on every page, that is naturally outside of the router view.

I want this sidebar to be partially populated by the page. The simplest way to do that is for the sidebar to define a `<portal-target name="sidebar">` and every page to define a `<portal to="sidebar">`

However, I want to pass the current state of the sidebar (minified or not) to whatever is currently populating the sidebar.

This could be done pretty easily, like this

sidebar.vue
```html
<portal-target name="sidebar" :is-minified="isMinified" />
```

page.vue
```html
<portal>
  <template #default="{isMinified}">
     ...
  </template>
</portal>
```

This would simply require to deconstruct the `$props` object received by `<portal-target>`, and to pass it to `<portal>` as scoped slot parameters.

**Comment by LinusBorg** [comment]
https://portal-vue.linusb.org/api/portal-target.html#slotprops

**Comment by lgarczyn** [comment]
Sorry for that, don't know how I missed it
