### ISSUE TITLE
Add support for SSG

### ISSUE THREAD

**Issue by xaddict** [LinusBorg/portal-vue#373]
portal-vue can be used in Nuxt and it works great in Server Side Rendered Mode and Live mode, but it breaks in Static Site Generator mode where the contents cannot be pre-rendered by the script Nuxt uses to do so.

When hydration works, the contents get inserted as soon as the javascript kicks in but it would be a major help if PortalVue supported pre-rendered static pages through Nuxt. This would make dynamic header images in Nuxt sites way easier to implement.

PS. I'm not sure if this is even possible while also supporting Vue, and I'm not sure if this is a Nuxt problem or a PortalVue problem. I just though to ask here.

**Comment by LinusBorg** [comment]
SSG won't really be possible with the technical approach I took for portal-vue.
