### ISSUE TITLE
Not working with Vue 2.7.0

### ISSUE THREAD

**Issue by optsing** [LinusBorg/portal-vue#376]
After upgrade Vue from 2.6.14 to 2.7.0 PortalVue stopped render anything.

The following errors are displayed in DevTools:
> [Vue warn]: $listeners is readonly.
> [Vue warn]: $attrs is readonly.

**Comment by xrado** [comment]
also noticed

**Comment by Sidnioulz** [comment]
Could either of you please test with 2.7.3? My colleagues are saying `portal-vue` works with that version.

**Comment by xrado** [comment]
tested again with the latest 2.7.5 and getting same errors as above

**Comment by LinusBorg** [comment]
A reproduction would be helpful, can you put something together?

This error appeared ages ago during unit test, but I have no idea how 2.7 could trigger that again.

**Comment by LinusBorg** [comment]
Great, thanks fornrhe Feedback.

Solution found in r linked issue
