### ISSUE TITLE
Mounting Portal cant find target

### ISSUE THREAD

**Issue by b-hayes** [LinusBorg/portal-vue#377]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/30540495/179936890-18bf721b-0d7a-4ca6-b978-7741bdd43658.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/30540495/179937388-1251f5df-f473-46f2-82ae-1573bc63050c.png">

Ive been following the example here: https://portal-vue.linusb.org/api/mounting-portal.html#example-usage

And I just cant seem to get this working is it me or an issue with Mount Portal?

**Comment by b-hayes** [comment]
Yeah, I have tried literally copying the example as well. Sorry I showed my adjusted attempt instead.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/30540495/179983331-ac024638-79e8-44b5-95a6-477481e9af4e.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/30540495/179983644-94b1af50-7693-48bd-b72e-4ca77b5f78e2.png">

**Comment by b-hayes** [comment]
also there is this warning if that helps:
`
[Vue warn]: Property or method "to" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <TestPortal> at assets/layouts/Admin/components/TestPortal.vue
       <AppLegacy> at assets/layouts/Admin/AppLegacy.vue
         <Root>
`

**Comment by LinusBorg** [comment]
1. The target should not contain a portal target. That's mounted for you.
2. The warning indicates that your component doesn't have a property called "to", which you are to pass to the MountingPortal.
3. The error indicates that the element you want to mount to (targetId) is not found in the document at the timr that you try to mount to it.
