### ISSUE TITLE
[Feature Request] Add TypeScript support

### ISSUE THREAD

**Issue by kingyue737** [LinusBorg/portal-vue#380]
Currently I need to add shims in all my projects to get intellisense and typecheck in template (powered by Volar):

```ts
import type { DefineComponent } from 'vue'

declare module 'vue' {
  export interface GlobalComponents {
    Portal: DefineComponent<{
      disabled?: boolean
      name?: string
      order?: number
      slim?: boolean
      slotProps?: any
      tag?: string
      to: string
    }>
    PortalTarget: DefineComponent<{
      multiple?: boolean
      name: string
      slim?: boolean
      slotProps?: any
      tag?: string
      transition?: boolean | string | object
    }>
  }
}

export {}
```
Autocomplete and typecheck:
![image](https://user-images.githubusercontent.com/40021217/189054046-641d2196-01d3-4bf7-a07d-3cb19af9e9d6.png)

Is it possible to add built-in support in this package? However, only Vue 2.7 and `@vue/runtime-dom` have `DefineComponent`.

**Comment by dschmidt** [comment]
See also: https://vuejs.org/guide/typescript/options-api.html#augmenting-custom-options
"Note this is just an example - well-typed libraries like vue-router should automatically perform these augmentations in their own type definitions."
This is about `ComponentCustomOptions` but the same applies to `GlobalComponents`.

Until then (depending on the build tooling) an even easier approach to set it up in downstream projects is the following:

```ts
// file needs to be an actual module, so we need at least one import or export
export {}

declare module 'vue' {
  interface GlobalComponents {
    Portal: typeof import('portal-vue')['Portal']
    PortalTarget: typeof import('portal-vue')['PortalTarget']
  }
}

```

**Comment by kingyue737** [comment]
Closing as Vue 2 has reached EOL
