### ISSUE TITLE
Document optimization

### ISSUE THREAD

**Issue by star-hs** [LinusBorg/portal-vue#381]
First of all, it's not a bug report, just advise. I installed this plugin to replace <Teleport> of vue3 in vue2. It's easy to use. just import then 'Vue.use'. 
Thus, I got an error in 'Vue.use', console displayed 't.provide is not a function'. I googled the error but got any related info. Finally, by debugging source code, I figured out I installed portal-vue@v3 which is used for vue3  because of installing without specific version.
All of blogs told me it's a plugin for vue2, so I never thought it can also support vue3. I am not sure if I was only one who made this mistake. if could, please mention it in README

**Comment by LinusBorg** [comment]
done
