### ISSUE TITLE
Make portal update process sync

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#39]
Inspired by #23, I think we can come up with a way to make the portal process sync:

1. create a unique id for each portal
2. send the id to the wormhole with each update
3. when a portal sends an update with `clear()`, the wormhole should only clear the contents if the current content is from the same portal

That way, we don't have to use an update queue and can get rid of the `$nextTick()` in the wormhole.

**Comment by LinusBorg** [comment]
Okay, that was easier than expected! Ready and tested locally, everything works!

Will merge soon.

**Comment by koczkatamas** [comment]
If I see correctly the code has been merged already (correct me if it isn't). Is there anything blocking this issue from being closed?

**Comment by LinusBorg** [comment]
Mainly me finding the time to release it. I initially planned to add one or two other thing before publishing it, but seeing how I currently don't find the time to do those things, I should do a quick release tonight.

Thanks for the gentel push ;)

**Comment by koczkatamas** [comment]
Oh great, thanks!

I did not want to hurry you, I just didn't know that the issues are closed only after they are released and I was unsure that the commit fixes the issue or there is still something to do. But good to know that everything is alright. (Hopefully I'll start using portal-vue soon.)

**Comment by LinusBorg** [comment]
> I just didn't know that the issues are closed only after they are released 

Yeah, usually people closed them once the issues are fiexed, right? 🗡 
I kept it around as a reminder.
