### ISSUE TITLE
Strange behavior and transitions not working

### ISSUE THREAD

**Issue by timyourivh** [LinusBorg/portal-vue#393]
## Context (reproduction)

I have an Laravel Inertia application.

In the layout I have:
The "fade" transition is included and works fine.

```vue
<PortalTarget name="title">
  <template #default="nodes">
    <transition name="fade" mode="out-in">
      <div v-if="nodes && nodes[0]">
        <component :is="nodes[0]" />
      </div>
    </transition>
  </template>
</PortalTarget>
```

In page **dashboard** I have:

```vue
<Portal to="title">Dashboard</Portal>
```

In page **account** I have:

```vue
<Portal to="title">Account</Portal>
```

In page **test** I have nothing, because A title can be missing and should not break the app.

## The issue:

There is no animation when navigation though the pages:

![portalvue-issue](https://user-images.githubusercontent.com/60601502/213483331-f1abede1-a04a-4db1-a845-21bcbee3c5d0.gif)
<sup>Example navigating from `dashboard -> account -> test -> account -> dashboard`</sup>

These alternative attempts yield the **exact same result**:

```vue
<PortalTarget name="title">
  <template #default="nodes">
    <transition name="fade" mode="out-in" duration="1000">
      <component :is="nodes[0]" v-if="nodes && nodes[0]" />
    </transition>
  </template>
</PortalTarget>

<!-- Even if I set the v-if to false it does not change anything -->

<PortalTarget name="title">
  <template #default="nodes">
    <transition name="fade" mode="out-in" duration="1000">
      <component :is="nodes[0]" v-if="false" />
    </transition>
  </template>
</PortalTarget>
```

## Strange behavior

Then this code yielded especially weird results:

```vue
<PortalTarget name="title">
  <template #default="nodes">
    <transition name="fade" mode="out-in" duration="1000">
      <div v-if="false">
        <component :is="nodes[0]" />
      </div>
      <div v-else>TEST</div>
    </transition>
  </template>
</PortalTarget>
```

Which results in:

![portalvue-issue2](https://user-images.githubusercontent.com/60601502/213486134-cd85b956-3c21-49c6-bf06-50226390a557.gif)
<sup>Example navigating from `dashboard -> account -> test -> account -> dashboard`. Note that page "test" does not contain a portal component</sup>
 
Even though the `v-if` is hard-coded to `false`, it still shows somehow?

I could not make any sense of it and could not get the transition to work, I am now going for an alternative approach but felt the need to share this issue in case it can get fixed or if someone runs into the same issue.

**Comment by ggedde** [comment]
@timyourivh Any updates on this. I am running into the same issue. Trying to migrate from 2 to 3 and I can't get any transitions to work.

**Comment by ggedde** [comment]
I got it to work, but was different then what I was thinking. In v2 it worked without needing any transition state as it seemed to handle the transition itself. I think with v3 it tries to hand that off to vue. So transitions don't seem to work just because the portal contents have been updated. It seems to now require a transition state. Ideally, I would prefer not to need to do this.

Also the docs say `<template v-slot:default="nodes">`, but it only works for me if I use `<template v-slot:wrapper="nodes">`

So here is my work around wherever you are specifying the <portal> content:
```
<portal to="target">
   <div v-if="loaded">
   ...
   </div>
</portal>
...
const loaded = ref(false);
onMounted(() => {
   loaded.value = true;
});
```

and the target
```
<portal-target name="target">
   <template v-slot:wrapper="nodes">
      <transition name="fade">
         <component :is="nodes[0]" />
      </transition>
   </template>
</portal-target>
```

**Comment by timyourivh** [comment]
@ggedde I decided to not use this package and fixed it by creating a "composable" like in nuxt 3.

You may find it useful so I'll dump my example here.
This is an inertia example but I'm sure you can create a solution that could be based off of this example. 

The composable looks like this:

```js
// resources/js/composables/usePageTitle.js

import { router } from '@inertiajs/vue3'

const initState = {
  text: '',
  icon: '',
  hasText: false,
  hasIcon: false,
  initialized: false,
  setTitle (text = '', icon = '') {
    this.text = text
    this.icon = icon
    this.hasText = text !== ''
    this.hasIcon = icon !== ''
  }
}

const pageTitle = reactive({ ...initState })

if (!import.meta.env.SSR) {
  router.on('navigate', (event) => {
    // Skip the first navigate event to prevent removal of title wehen the page is being loaded the first time.
    // #KISS
    if (!pageTitle.initialized) {
      pageTitle.initialized = true
      return
    }

    Object.assign(pageTitle, initState, {
      initialized: true // Stay initialized.
    })
  })
}

export default function usePageTitle () {
  return pageTitle
}
```

Now if you import the usePageTitle on every page (or auto import it using [unplugin-auto-import](https://www.npmjs.com/package/unplugin-auto-import)). You can do this on every page:

In your pages:
```vue
<script setup>
// I use auto import to import the entire 'composables' directory. Nuxt like behavior. 
// import usePageTitle from '~/js/composables/usePageTitle'

usePageTitle().setTitle('Home', 'mdi mdi-home')
</script>
```

In your layout:
```vue
<script setup>
const pageTitle = computed(() => usePageTitle('Home', 'mdi mdi-home'))
</script>

<template>
  <transition-group name="fade" mode="out-in" duration="100">
    <div
      v-if="pageTitle.hasIcon"
      key="icon"
      class="text-2xl"
      :class="pageTitle.icon"
    />
    <div
      v-if="pageTitle.hasText"
      key="text"
      class="text-2xl font-medium capitalize"
      :class="{ 'ml-2': pageTitle.hasIcon }"
      v-text="pageTitle.text"
    />
  </transition-group>
</template>
```

I'm going to close this issue because I don't think it will be fixed anyway.
