### ISSUE TITLE
$parent

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [LinusBorg/portal-vue#394]
can;t access $parent from portal i.e method from parent component  addsomthing() 

this.$parent.addsomthing()

this.$parent.addsomthing is not a function

https://stackoverflow.com/questions/46208610/call-parent-method-with-component

**Comment by LinusBorg** [comment]
Yeah that's expected and not really fixable.

https://portal-vue.linusb.org/guide/caveats.html#parent

**Comment by gotshadowbantempaccount** [comment]
@LinusBorg thank you,  just fixed now by just passing function as prop
