### ISSUE TITLE
Getting error while importing

### ISSUE THREAD

**Issue by Sathish1390** [LinusBorg/portal-vue#405]
![portal-vue-error](https://github.com/LinusBorg/portal-vue/assets/20921310/67b830af-1b56-4077-b5e0-9ecfd9759606)

**Comment by LinusBorg** [comment]
The current major version of portal-vue is for Vue 3.

You seem to be using Vue 2, so install portal-vue@2

Docs for that version: https://v2.portal-vue.linusb.org/

**Comment by Sathish1390** [comment]
It worked. Thank you so much!! @LinusBorg
