### ISSUE TITLE
Rename to vue-portal?

### ISSUE THREAD

**Issue by Nirazul** [LinusBorg/portal-vue#44]
As [this project](https://github.com/vue-comps/vue-portal) is marked deprecated, you could ask the author if you can use its name in favour of `portal-vue` so that my OCD doesn't trigger when i look at my package.json :D

**Comment by LinusBorg** [comment]
>  so that my OCD doesn't trigger when i look at my package.json :D

Great Idea, I'll try and get in touch with the author.

**Comment by LinusBorg** [comment]
Ok so I openen an issue here: vue-comps/vue-portal#1

**Comment by Nirazul** [comment]
Afaik you can unpublish older versions so they won't pop up in the history.

**Comment by LinusBorg** [comment]
> Afaik you can unpublish older versions so they won't pop up in the history.

Oh no, I don't want to create my own small "left-pad" incident :D

**Comment by LinusBorg** [comment]
Just a small update: The owner generously agreed and tranferred ownership to me.

However, making this switch will have to wait a bit, I have to plan this in order to not break anything for users of the old package etc (never done this).

Be patient please ;)

**Comment by LinusBorg** [comment]
I'm not sure that this stil makes sense - The package is now already quite known as "portal-vue". I will re-evaluate doing the switch when we reach `v2` but it will probably take a while.
