### ISSUE TITLE
Remove the wrapper element of PortalTarget?

### ISSUE THREAD

**Issue by mystrdat** [LinusBorg/portal-vue#48]
The portal leaves a div with a class of `vue-portal-target` in the DOM when there is nothing to render and renders any ported content inside this div. The expectation is that this div doesn't exist and the portal contect is directly placed inside the target destination without any additional bullshit wrappers. Why is this and how can I get rid of it?

**Comment by mystrdat** [comment]
Ok then. Might be nice to mention in docs.

`<portal-target tag="my-element"></portal-target>`

**Comment by LinusBorg** [comment]
> without any additional bullshit wrappers.

1. Each component in Vue needs a root element, there's no way around that, currently.
2. However, if the render function doesn't return anything, Vue will render a comment node (`<!-- -->`) to have some element to bind the instance to.

We could switch to that, after testing it.

> Might be nice to mention in docs that the element can be changed.

[That is mentioned in the docs](https://linusborg.github.io/portal-vue/#/docs/portal?id=tag).

> but still, the enforced DOM layout is not nice thanks to the wrapper being left in even while the portal isn't used. This disables reasonable styling for this element, because it could block interaction with the rest of the page even though it carries no content.

Out of curiosity, because I occationally suck at CSS: In what way is a `display: none;` element hindering design? When trying to use sibling selectors?

**Comment by mystrdat** [comment]
>  When trying to use sibling selectors?

That's quite dependent on your layout, the fact that it exists means it has to be handled and there is no scenario where this element is an advantage. It could break nth-child, flexbox stacking, siblings.. Setting it to something like `node:empty { display: none }` is a poor bandage, especially with iOS reflow bugs on such selectors.

> Each component in Vue needs a root element

I'm aware that components need to have a wrapping element and it's much more of a problem in React than in Vue, but the existence of features that wrap other elements without adding blank divs everywhere, like `<transition>` vs `<ReactCSSTransitionGroup>` or replacing the mounted element, makes me believe Vue has ways to work around this, although it's speculation on my part as I'm still fresh to the framework.

**Comment by LinusBorg** [comment]
Oh damn, I misread the title and thought you were talking about the placeholder element left by `<portal>`, but you are talking abouot the wrapper element rendered by `<portal-target>`!

As a result we have been talking past each other so far. Sorry, I'm a bit dense today, my mistake.

The good news is that for that case, I think I should have you covered with the [`slim` option](https://linusborg.github.io/portal-vue/#/docs/portal-target?id=slim).

**Comment by mystrdat** [comment]
> `slim`

!!! That's exactly what I'm looking for. I guess I have failed reading the docs, thanks for the great help.
