### ISSUE TITLE
Convert components to *.js (solve inject-loader issues)

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#52]
We don'T need .vue files because we don't have any templates or styling.

The only reason for using -vue files is that for some reason, inject-loader (v2 and v3, no difference) won't work with normal .js files, and I can't figure out what's wrong.

When I have time I should switch file format and solve this inject-loader problem somehow.

**Comment by m1neral** [comment]
Hello!
How I can try library when I use *.vue files in project?
