### ISSUE TITLE
Use case: Modals under CSS containment

### ISSUE THREAD

**Issue by FlorianDold** [LinusBorg/portal-vue#56]
Another pretty convincing use for portal-vue is showing modals from within components under [CSS Containment](https://drafts.csswg.org/css-contain/) (see [this](https://developers.google.com/web/updates/2016/06/css-containment) a friendlier introduction).  Here portal-vue allows showing modals, and at the same time reap the performance benefits of CSS containment.

I would suggest adding this to the documentation!

**Comment by LinusBorg** [comment]
Thanks for this suggestion @FlorianDold 

However I have to admit that I don't know a thing about that `containment` property and am unsure if portal-vue actually helps here. I skimmed through the "friendlier" introduction and kind of get the overall goal of this property, but something importat still eludes me I think.

Could you elaborate a bit as to what advantages portal-vue has in this context?

**Comment by FlorianDold** [comment]
Let's say `MyComponent` is vue component within a complex app that uses the `containment` property to speed up rendering.  Now `MyComponent` wants to show a modal dialog with one of the existing libraries for that, such as [modal-vue](https://github.com/colinf/modal-vue).  The template for `MyComponent` will look something like this:

```html
<template>
  <!-- content of MyComponent -->
  <modal :showModal="show">
    <h1>Hello, I'm a modal</h1>
    <!-- more modal content -->
  </modal>
</template>
```

Unfortunately this won't work!  The modal should be shown full-page, but due to the `containment` property, all children of `MyComponent` are clipped to the dimensions of the root element of `MyComponent`.

Using portal-vue though, you can teleport the modal dialog outside the confined area of `MyComponent`, to some part of the DOM that doesn't have `containment`.  It would look something like this:

```html
<template>
  <!-- content of MyComponent -->
  <portal-target name="modal">
    <modal :showModal="show">
      <h1>Hello, I'm a modal</h1>
      <!-- more modal content -->
    </modal>
  </portal-target>
</template>
```

Now the modal isn't a DOM child of a container (with `containment`) anymore and shows up properly.

**Comment by LinusBorg** [comment]
Thank you very much for this explanation. That made the pieces fall into place for me.

I'll inlcude this into the docs when I add new examples. Could take awhile though.

Thanks again!
