### ISSUE TITLE
Transition Support?

### ISSUE THREAD

**Issue by dts** [LinusBorg/portal-vue#59]
This naive use case doesn't work for me:

```
      <transition name="fade">
        <portal-target name="title" slim @change="titleChange">
          Title
        </portal-target>
      </transition>
```

After reading some of the code, I guess I'm not really sure why - I don't understand the `transition` component enough to speculate.  Am I missing something?

**Comment by dts** [comment]
I did a little more digging, and figured out that transitions work if I embed the transition logic inside the component itself, with one weird caveat.  When I do some transitions, it doesn't pick up the change, because the container element hasn't changed.  Once I added keys, this fixed it to some degree, but the emitChange location appears to be fired after an important render occurs - and you wind up with two copies of the new thing during a transition instead of one old and one new the way Transition normally works.

**Comment by LinusBorg** [comment]
Thanks for bringing this up. To be honest I haven't thought about or tested transitions with this so far, but I probably should.

Could you maybe provide a working demo of the scenario you described so I can inspect it?

**Comment by dts** [comment]
Here's an example:  https://github.com/dts/portal-vue/tree/transitions  - see the "toggle" one.  I'd love to have the transition defined outside the portal, but I understand if there's a limiting factor in there.  Otherwise, being able to specify the same options as the transition node would be great (Nuxt has a great implementation of passing props & callbacks to an internal transition node). 

The behavior I want is to be able to have a "portal" defined in the toolbar/navbar of a mobile app, and then broadcast the new title and right-side-button into the thing, and have it do individual transitions for each (because title & right-side are both separate portal targets).  Does that make sense?

**Comment by LinusBorg** [comment]
Thanks, will take a look! :)

**Comment by LinusBorg** [comment]
So I'm working on this. So fsr: 

1. Wrapping the portal-target doesn't work, and I don't think it can, really. 
2. Using the transition inside the content we send from *one* portal works
3. Doing the same with more thayn or source portal is under test. 
4. I added a prop to portal-target that can wrap the content in a transition. It works so far, but with a caveat: it also animated during initial render, as if `appear` was set. 

So I will make **4.** a feature even if I can't remove the caveat right now, and I will further test how well transitions work when being passed from multiple (exclusive) portals and hope to get some examples up in  the docs for all 3 ways to do this.

**Comment by dts** [comment]
Thanks!

Why do you think (1) is true?  I'm unfamiliar with the details of render functions, so I may be missing something crucial.  For 4 - how do you pass the animation details to the inner transition element?  If that passthrough is controlled by portal-vue, it should be really easy to just pass in "no transition" on initial render, right?

**Comment by LinusBorg** [comment]
> Why do you think (1) is true? I'm unfamiliar with the details of render functions, so I may be missing something crucial.

Well, I meant to say it won't be solvable within the components we currently have (Portal / Wormhole / PortalTarget). Because as I think you have already found out yourself, you have to set a unique key on the `<portal-target>` to make `<transition>` actually do what you want it to - and we can't do that from "within".

What might work is to provbide some sort of wrapper that does extract a suitable key from the Wormhole and sets it on the portal-target. But that would mean to create another component and introduce additional code which I want to avoid until I'm sure that we can't solve with something like **4.**

> For 4 - how do you pass the animation details to the inner transition element? If that passthrough is controlled by portal-vue, it should be really easy to just pass in "no transition" on initial render, right?

That's actually not a bad idea and I will try it out asap. But it's possible that the issue lies deeper within Vue's transition system (which I must admit I haven't fully understood the internals of, yet), so let's see if this gets us far enough.

If it does, it would mean that we can solve out issues within `portal-vue` and don't need to introduce a wrapper or anything more complicated.

**Comment by LinusBorg** [comment]
So I have good news, your idea seems to work well actually. I just finish up some tests and then will merge & publish this weekend.

**Comment by LinusBorg** [comment]
Damn, will have to postpone this release. Found some bug along the way - it's not that easy after all ..

**Comment by dts** [comment]
Ah well / but transition-group is a welcome addition!  Let me know if you need/want any help - I'm happy to lend a hand if you have specific things that could use extra eyes.

**Comment by LinusBorg** [comment]
I think i have it figured out, but want to try and add a few more tests. 

Skipping the whole `transition` component during the initial render of the portal doesn't really work, so i now changed to rendering the `transition` component initially as well, but don't apply the real transition props until the first re-render. (so the transition runs, but with a "fantasy" transition name that won't trigger any actual CSS or JS transition.

It works, but I 'm not sure yet if it's reliable in different scenarios, like different order of `<portal>` and `<portal-target>` in the document flow, and different content-switching scenarios.

I may push the feature branch later so you can take a look if you want to, but I'm on mobile right now.

**Comment by dts** [comment]
That'd be great - portal-vue, if it were to support animations, would allow me to build a mobile framework that does things correctly :).

**Comment by LinusBorg** [comment]
Ok, I will push it tomorrow afternoon after I did some small tests. the API would look like this:

```html
<portal-target
  slim
  :transition="{ name: 'fade', mode: 'out-in', enterClass: 'fade-special-enter' }"
  :transition-events="{ enter: handleEnter, ... }"
  />
```

With `slim` set, it will render a `<transition>` (so only one root node allowed at a time), without it, it would render a `<transition-group>` (for multiple elements - from one source, mind you. multi-source-support is still another thing to tackle).

**Comment by dts** [comment]
What prevents multi-source?  I get the feeling that there's something I'm fundamentally missing about render functions and/or Vue in general - and I haven't been able to articulate it and also reading the code hasn't helped me understand it at all...

**Comment by LinusBorg** [comment]
Not mcuh., I just need some time to find a nice (preferably backwards-compatible) API for it and actually write it. 

Since I cache all sent vnodes in a store object, I cannot concatenate the vnodes that are being sent -that would lead to duplicated content whenever one of the sources re-renders.

So it has to be smarter than that, and dev have to be able to easily determine the order of the content by source for this to be really useful.

**Comment by dts** [comment]
Oh, interesting.  My use case requires multiple sources, so I'll hold off on jumping ship from my currently bad (but working) structure.  Basically, when a new route shows up with, for example, a title element to be displayed in the title bar, I want it to animate between the old one and the new one.  Currently I do this by defining functions on the object, and having the title bar check the results of those functions during transitions.  I might switch those over to render functions, so it's more flexible, but a portal would be much easier to read & understand (if they can animate between sources).

**Comment by dts** [comment]
Also, huge thanks for your efforts on portal-vue!

**Comment by LinusBorg** [comment]
You are misunderstanding - you can *switch* sources, that's fine. You just can't show content from multiple sources at the dame time.

**Comment by dts** [comment]
Oh, my bad, and it animates between source switches?

**Comment by LinusBorg** [comment]
Yes.

**Comment by LinusBorg** [comment]
@dts Here's the feature branch: https://github.com/LinusBorg/portal-vue/tree/feature/transition_support_%2359

Keep in mind it's not considered production-ready yet, but the API is stable.

**Comment by LinusBorg** [comment]
@dts Did you have time to give this a spin? I would like to release it this weekend.

**Comment by dts** [comment]
I've been using it, but I didn't spend enough time with it to get it exactly working for my use case, but it looked like it was working as advertised.

**Comment by dts** [comment]
Mostly I need to fiddle with the animation.

**Comment by LinusBorg** [comment]
Thanks for the feedback!

**Comment by andrewcourtice** [comment]
Hi @LinusBorg 

Firstly, thank you for taking the time to write this tool. It works perfectly.

I was just curious how far away you are from releasing the updated version with transition support? I've run into a situation where I need to transition a component in a portal and was keen to test out your changes.

Thanks again!

**Comment by LinusBorg** [comment]
I wanted to have it released already, but unfortunately private stuff is keeping my available time to a minimum at the moment. 

These impediments should be over next week, and since the feature is done, I hope that I can prepare the release at the weekend of next week.

**Comment by andrewcourtice** [comment]
@LinusBorg No worries.

Thanks again. 

Turns out I got the transitions working in the current release by using `transition` inside `portal` with `v-if` on the transitioning element as opposed to the portal. In other words, instead of:

```html
<portal to="portal-name" v-if="showComponent">
    <my-component></my-component>
</portal>
```

I just did:

```html
<portal to="portal-name">
    <transition name="my-component-transition">
        <my-component v-if="showComponent"></my-component>
    </transition>
</portal>
```

That seems to work pretty well...

**Comment by LinusBorg** [comment]
Ywah, forgot to mention that third world as we'll n many, but not all situations.
