### ISSUE TITLE
Error in nextTick: "TypeError: Cannot assign to read only property 'isRootInsert' of object '#<VNode>'"

### ISSUE THREAD

**Issue by AlexandreBonaventure** [LinusBorg/portal-vue#62]
When using the new Wormhole API (copying the example from doc) i get this Error:
`Error in nextTick: "TypeError: Cannot assign to read only property 'isRootInsert' of object '#<VNode>'"`

vue@2.3.4

**Comment by LinusBorg** [comment]
So of it be possible to see some example code, or better, a reproduction?

**Comment by AlexandreBonaventure** [comment]
Sorry I didn't give any additional information cause it's directly related to the PR. It happens when passengers is a VNode instead of [VNode]. That's why example is broken.

I'm closing this. Thanks for maintaining this package
