### ISSUE TITLE
The object does not support a property or method " includes " (IE11)

### ISSUE THREAD

**Issue by gewisser** [LinusBorg/portal-vue#64]
Hello.

Browser **Internet Explorer 11** (The object does not support a property or method " includes "):

![image](https://user-images.githubusercontent.com/5417292/29666808-8d03fb74-88e2-11e7-9093-87b6af305b90.png)

> portal-vue.js:

![image](https://user-images.githubusercontent.com/5417292/29666814-9bb02b7a-88e2-11e7-994d-24cc4b9a3d34.png)

**Comment by LinusBorg** [comment]
Thanks!

I hope to do a general cleanup release soon, hoefully this week, and will clean this up as well.

In the meantime, you can help yourself out by including a polyfill for this method:

https://github.com/zloirock/core-js/blob/master/fn/array/includes.js

**Comment by gewisser** [comment]
Thanks!
