### ISSUE TITLE
Hydration error with Nuxt/SSR

### ISSUE THREAD

**Issue by iamdubx** [LinusBorg/portal-vue#65]
Hello. I got an error when trying to use with Nuxt

```
vue.runtime.esm.js:430 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```
I have Modal component, that I want to render outside of component, where I am calling modal. 

I have this:

This is where I want to render Modal component:
```
<template lang="pug">
  div
    my-header
    .flex-sticky
      nuxt.content
      my-footer
    portal-target(name="destination")
</template>
```

This is where I am calling Modal component
```
<template lang="pug">
div
    portal(to="destination")
        modal
</template>
```

Sorry for Pug.

**Comment by iamdubx** [comment]
I just tried `no-ssr` but it didn't help.

**Comment by iamdubx** [comment]
I tried `no-ssr` on portal-target, on portal and on component itself. All three options didn't work.

![ssr-portal](https://user-images.githubusercontent.com/30086515/29750679-11ecfeea-8b12-11e7-9a3c-afff7819783c.png)

**Comment by iamdubx** [comment]
https://github.com/LinusBorg/portal-vue/issues/36

**Comment by egoist** [comment]
`'no-ssr': NoSSR` or `NoSsr`

**Comment by iamdubx** [comment]
In components? No changes unfortunately..

**Comment by iamdubx** [comment]
I see `no-ssr` tag in markup, don't know if it means something.

**Comment by iamdubx** [comment]
https://gist.github.com/iamdubx/6501a95e66bc99ef4d261b76b4621f13

**Comment by iamdubx** [comment]
Issue fixed. I had to wrap this component in 3 different places to make it work :smile:

**Comment by gustawdaniel** [comment]
Now there is <client-only> recommended instead of <no-ssr>

```
    <client-only>
      <PortalTarget name="under-header"/>
    </client-only>
```

> https://medium.com/@liutingchun_95744/nuxt-js-best-practices-for-client-side-only-contents-client-only-no-ssr-4843e94d9565
