### ISSUE TITLE
Use Case: menu items from within each page

### ISSUE THREAD

**Issue by miljan-aleksic** [LinusBorg/portal-vue#66]
Perhaps a use case to add on the website:

When in a complex App there could be a general Menu which Items change on each view (a route page). Declaring the menu items in Vuex is limited, as you may want different reactions for each item (change route, apply some action to data, etc). Ideally you would declare those items in the view template but avoid redeclaring the entire menu again and again. PortalVue solves it nicely.

**Comment by LinusBorg** [comment]
I think I actually have exactly that use case as an example codpen in the docs, could you take a look and tell me if that's what you had in mind? 

https://linusborg.github.io/portal-vue/#/examples?id=dynamic-sidebar-content

**Comment by miljan-aleksic** [comment]
Ah yes, it is. I was looking into [Why](https://linusborg.github.io/portal-vue/#/getting-started?id=but-why) section.

BTW, I think there is a typo in that example: `Bu selectively rendering different...`

**Comment by LinusBorg** [comment]
Good catch. My typing is generally horrible, so there sure as hell are more than that one :D

**Comment by miljan-aleksic** [comment]
heheh

Before closing this issue, a question if I may: Is there a way to avoid rendering the `vue-portal-target` div wrapper? Is getting on the way of the library CSS.

**Comment by LinusBorg** [comment]
There currently isn't, but it would tehcnically be possible to allow this. Vue would then render a comment node to have something to bind the instance to. Shuldn't be a biggy.

Please open a seperate issue for this, with a short explanation of how this is getting the way of your CSS.
