### ISSUE TITLE
PortalTarget should not create rootNode if slotContent has only one vNode

### ISSUE THREAD

**Issue by LinusBorg** [LinusBorg/portal-vue#8]
This could be made optional with a `slim` prop.
```html
<portal to="destination">
  <p>Content</p>
</portal>

<!-- Renders a div with the content inside: -->
<portal-target name="destination" /> 

<!-- Renders no div , only the `<p>` from the content: 
       Would still create a root div if content had more than one root node.
    -->
<portal-target name="destination" slim /> 
```

**Comment by LinusBorg** [comment]
done, tests missing.

**Comment by LinusBorg** [comment]
tests added

**Comment by nodegin** [comment]
I am curious why the `slim` was not added by default, or in other word, why it is necessary to render an extra `<div>`?

**Comment by LinusBorg** [comment]
Because every component (including portal-target) needs one root node. Since you can pass one or more nodes though the portal slot, we render one root node around them by default, preventing errors if more than one node is passed. 

By choosing the slim attribute, you are consciously choosing to only pass one node, so we can leave it out.
