### ISSUE TITLE
Component scope

### ISSUE THREAD

**Issue by marcmascarell** [LinusBorg/portal-vue#81]
Hi,

I'm considering this package to allow users to extend components functionality in my package https://github.com/marcmascarell/artificer. The problem I have is that given that the code that would extend is third-party I don't know which is the best approach to give them the ability to hook into my components and add functionality.

Searching I found this, and looked like a good choice but I faced the problem that it looks like it does not allow passing an scope to the portal-target component, am I wrong? Could this be done? (https://codepen.io/anon/pen/BwVvdV)

I would like something like https://vuejs.org/v2/guide/components.html#Scoped-Slots 

For example (not working example): https://codepen.io/anon/pen/MEXPpj

Do you think this library is a good fit for my use case? If not, do you have another recommendation?

My other alternative right now is generating the code from server side...

Thanks in advance.

**Comment by LinusBorg** [comment]
Hi @marcmascarell 

You are right, portal-vue doesn't support scoped slots right now. I will think about wether this makes sense as a new feature, but even if I find it does, it won't happen very quickly.

**Comment by LinusBorg** [comment]
Already got this working locally, just have to finish tests :)
