### ISSUE TITLE
Show only the last portal connected to a target

### ISSUE THREAD

**Issue by zicklag** [LinusBorg/portal-vue#84]
I have a use case where I use portal-vue to allow sub-routes in my app to set certain layout elements on my page such as the header. The sub-route uses a portal to render the header because the sub-route is deeply nested in the DOM and the layout slot containing the header is not.

Because I have nested routes, it would be really useful if I could tell the portal-target for the header to render only the *last* or *deepest* portal that was connected to it instead of the first portal that is connected to it. That way deeper sub-routes could override the header that is set by the higher level sub-routes.

It would be convenient if this was a prop on the portal-target component.

**Comment by LinusBorg** [comment]
The portal-target always displays the *last* content update it receives. Which is the last, depends on the appearance of the portal in the document flow.

So you could simply achieve that by rendering the parent's portal before you render the subroute's portal.

Howeber, I would rather try to always only render the portal that you really need, i.e. by using a v-if
```javascript
<portal v-if="$route.name='subroute-name'">

</portal>
```
