### ISSUE TITLE
Cloning support

### ISSUE THREAD

**Issue by paparent** [LinusBorg/portal-vue#89]
Hi!

I know that it might sounds weird but here's a usecase:

I want to support fixed header for a table. I'm able to teleport the <thead> at the top, at fixed area, but need to deal with columns width. One way I found is to clone the <thead>. It works great. I added a `clone` option like that: https://github.com/paparent/portal-vue/commit/4befe833323e61781b0192bdaca9c55bb7933bc1

One problem is: on the original <thead>, the elements inside doesn't update! seems like update is only sent to destination, but not the original. Is there a way to achive this? 

Thanks !

**Comment by LinusBorg** [comment]
That sounds useful, but I'm afraid a proper support for this is not as easy as the change you made. 

Vnodes should never be used in more than one place, so if we want to make this possible, we really need to clone those nodes. 

I think the best approach for that would be to use the scoped slot functionality of Vue, so this feature will depend on #81

**Comment by LinusBorg** [comment]
So, I just finished the slot feature, which was required to make this clone feature.

But as I was playing with it, I think the usecase is too small to justify adding an extra API for it.

Instead, what you can do once I released `1.3.0` it to build the clone functionality on your own with a small functional wrapping component:
```javascript
// cloning-portal.js
export default {
  functional: true,
  props: [ 'to' ],
  render: (h, ctx) => {
    // We create a Portal and pass the scoped slot to it
    const portal = h('portal', {
      props: ctx.props,
      scopedSlots: { default: this.$scopedSlots.default },
    })
    // We also run the scopedSlot function, using the component's attrs as its props (if any)
    const content = this.$scopedSlots.default(ctx.attrs)
    // then we render content and portal to the DOM:
    return h('div', {}, [...content, portal])
  } 
}
```

### Usage

```html
<cloning-portal :to="target">
  <div slot-scope="_">
    <p>Your Content here</p>
  </div>
</cloning-portal>
```

You have to use a scoped slot, even if you don't need to pas props to it. Otherwise we can't duplicate the vnodes in a secure fashion.

**Comment by paulgeisler** [comment]
For someone who is searching for a solution:
https://codesandbox.io/s/5mjo9r63k

**Comment by PayteR** [comment]
> For someone who is searching for a solution:
> https://codesandbox.io/s/5mjo9r63k

I tried this but it gives me `Cannot read property 'default' of undefined`
