### ISSUE TITLE
When rendering outside of the Vue-App, target's existing classes are removed

### ISSUE THREAD

**Issue by mikerogerz** [LinusBorg/portal-vue#90]
Target's existing classes are removed and replaced by only "vue-portal-target", instead of merging with the existing classes. This worked correctly in the previous version, 1.1.1.

**Comment by LinusBorg** [comment]
Hm. Strange, I *thought* I didn't touch that part of the code. Will check it out, thanks!

**Comment by LinusBorg** [comment]
Okay, so I can verify this, but the bad news is I can't really tell why it's happening. The component is re-rendering (which seems odd enough on its own), and even though the element attributes should be updated after re-renders, they aren't.

I'll dig some more and maybe have to do a bigger refactor for that section.

And tbh another reason for me to drop this feature in `2.0` and let users handle this on their own with a simply `new Vue()` (see: #74)

Though I will get this working again for `1.*` ;)

**Comment by mikerogerz** [comment]
Appreciate the help. For now I'll just temporarily downgrade.

**Comment by mikerogerz** [comment]
Works great now, thanks.

**Comment by LinusBorg** [comment]
Yay :)
