### ISSUE TITLE
Error in render: "ReferenceError: 'Symbol' is undefined" when run on IE11

### ISSUE THREAD

**Issue by dtsao** [LinusBorg/portal-vue#93]
Using the vue-webpack template 1.2.6 and portal-vue 1.2.1. My index.html has some complicated markup for the page header/footer including some navigation links. Vue is controlling a div in the middle of the page.  I am using portal-vue to set the navigation links in the header based on some process.env variables from a config file so these can be customized for dev/qa/prod. This is working fine in Chrome and Firefox, but is failing in IE11. In IE11, the original contents of header div targeted by portal-vue is removed but is not being replaced by the portal content. The console is giving the following errors. How do I troubleshoot?  
 
![image](https://user-images.githubusercontent.com/4969981/34010469-d7e827aa-e0da-11e7-8399-b746ea7e800d.png)

Thanks

**Comment by LinusBorg** [comment]
Hard to say without knowing any of your code. 

Portal-vue doesn't use Symbols, so my first quesr would be to find out where that 'Symbol' us coming from...

**Comment by dtsao** [comment]
@LinusBorg, I created a simple project reproduces the error on 2 different Windows 10 PC running IE11 with node v6.11.5 or v8.9.3: https://github.com/dtsao/portal-vue-test-ie11

The error occurs when running using the webpack dev server and IE11, **but goes away when running a production build.**

My IE11 version:
![image](https://user-images.githubusercontent.com/4969981/34073073-fcab0e78-e25f-11e7-9369-2b49f43c6245.png)

Chrome:
![image](https://user-images.githubusercontent.com/4969981/34073101-934bc73c-e260-11e7-8657-1a9218960765.png)

IE11 - note that the portal-vue content is missing:
![image](https://user-images.githubusercontent.com/4969981/34073111-be3c6f78-e260-11e7-8efe-518258c97048.png)

Console:
![image](https://user-images.githubusercontent.com/4969981/34073127-f8c997e2-e260-11e7-8b7e-bb739c0e3dbc.png)

Step through exceptions to find the matching error:
![image](https://user-images.githubusercontent.com/4969981/34073139-239b8764-e261-11e7-938b-189bbe5e0d79.png)

![image](https://user-images.githubusercontent.com/4969981/34073144-2ea54924-e261-11e7-9caa-ac0f2f601f9b.png)

![image](https://user-images.githubusercontent.com/4969981/34073145-36b38b94-e261-11e7-91ff-6ec5f0e94b05.png)

etc.

On my full blown application, the error is in line 5 of: node_modules\core-js\library\modules\_iter-detect.js
![image](https://user-images.githubusercontent.com/4969981/34073589-928d40e6-e26a-11e7-8312-c0a01e648222.png)

**Comment by LinusBorg** [comment]
Ah, I see. now I get it. The source for that passage is this:
```javascript
export function combinePassengers (transports) {
  let passengers = []
  for (const transport of transports) {
    passengers = passengers.concat(transport.passengers)
  }
  return passengers
}
```

the `for ... of` doesn't work without a polyfill. I'll change that to an ES5 counterpart.

**Comment by LinusBorg** [comment]
See #94

**Comment by dtsao** [comment]
Great - thank you for the fix!
