### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by frlinw** [LinusBorg/portal-vue#98]
Hi,

vue: 2.5.13
portal-vue: 1.3.0-beta.0

I have a basic usage of portal-vue for modal display (because sadly (or not) z-index is relative)
```
<portal-target name="modal" transition="modal-transition"></portal-target>

<portal to="modal">
    <router-view></router-view>
</portal>
```
I got the following breaking error (there is only one modal at a time)
`[Vue warn]: <transition-group> children must be keyed: <>`
I fixed it with `slim` props but is it a normal behavior ?

Other thing, transition works fine on the initial state if used like this:
```
<portal to="modal">
    <router-view>
           /* 
             <transition name="modal-transition">
                    <div class="modal"></div>
            </transition>
          */
    </router-view>
</portal>
```
But the `leave` part of the animation is ignored. 
Is it possible to get the animation duration then clean the portal-target after it ends ?
Because ideally, I see portal-vue as an option. If I have to move the transition part of a component to get it works, its behavior with or without portal will be different and it's a problem.

Thanks for your work on this lib!

**Comment by LinusBorg** [comment]
> is it a normal behavior? 

Yes it is. Without the slim prop, a transition-group is used, and as the error states, it's children need a `key`.

For the second problem I would need to see some actual code that I can run.

**Comment by frlinw** [comment]
Thanks for the quick answer. I'll update with a demo asap

**Comment by frlinw** [comment]
Harder than expected to reproduce in a codepen, I'll create a dedicated repo

**Comment by frlinw** [comment]
Repo: https://github.com/frlinw/vue-portal-transition-leave-issue
Demo : https://powerful-plains-56797.herokuapp.com

**Comment by LinusBorg** [comment]
thanks, will take a look in the coming days. I'm a bit short on time at the moment, unfortunately.

**Comment by tinymachine** [comment]
+1 on the `leave` part of the transition being ignored (vue: 2.5.11, portal-vue: 1.3.0).

Repo: https://github.com/tinymachine/vue-portal-transition-issue
Demo: https://vue-portal-transition-leave-issue.netlify.com

Thanks for open-sourcing this project!

**Comment by kfirba** [comment]
The enter transition works just as expected but the leave transition never triggers. Any news on that issue?

**Comment by redplant3d** [comment]
Hi @kfirba , it's because of the this.$el.innerHTML = '' in the portal-target.js.
`  
beforeDestroy() {
    this.unwatch()
    this.$el.innerHTML = ''
  },
`
@LinusBorg: Does the removal of the innHtml-line have any sideeffects?

**Comment by LinusBorg** [comment]
Good catch. I remember I put it there for some reason, but forgot what it was, to be perfectly honest.

Maybe it might not be necessary (any longer)

**Comment by kfirba** [comment]
@redplant3d Good catch.

@LinusBorg Any plans to address this? Do you need us to check something?

**Comment by LinusBorg** [comment]
Yes I'm planning to address this, but I'm still struggling to make time for this project sind February. Was moving, had a huge project at work and so on. 

My schedule will relax considerably around the end of June, but before that' i won't be able to much.

If you want to submit a PR with this line removed and passing tests, that would be appreciated.

**Comment by thomasaull** [comment]
+1 for this, I just ran into the same issue :)

**Comment by tinymachine** [comment]
I might be missing something, but I updated to the `1.4.0-beta.1` version and I'm still seeing the issue of the leave transitions not displaying:

[1.4.0-beta.1 example](https://portal-vue-1-4-0-beta-1--vue-portal-transition-leave-issue.netlify.com)
[1.3.0 example](https://vue-portal-transition-leave-issue.netlify.com)
(links to repos appear in the examples)


Any help you can offer would be great -- thank you!
